### ISSUE TITLE
Jersey jar Causes issues

### ISSUE THREAD

**Issue by kalyanjennu** [nginx-clojure/nginx-clojure#100]
Hi, adding Jersey jars inside the nginx-clojure.jar causes issues with our application. Because we are using different version of jersey jars. It could help if you keep both of them separate.

**Comment by xfeep** [comment]
@kalyanjennu  In fact we keep both of them separate always. nginx-jersey is a sub project of nginx-clojure and it gets its own jar file when we build it. nginx-clojure.jar has nothing dependent on jersey.
