### ISSUE TITLE
Is NginxJavaRingHandler single-threaded?

### ISSUE THREAD

**Issue by 3thinkthendoit** [nginx-clojure/nginx-clojure#105]
hi ，我测试后发现NginxJavaRingHandler是单线程模型。可否简单说一下nginx-clojure的设计原理，多谢。底层通信是否基于nginx的特性。

**Comment by xfeep** [comment]
nginx-clojure has three kinds of I/O modes :

1. single-threaded
2. thread pool 
3. coroutine pool

Please follow [this link](http://nginx-clojure.github.io/configuration.html#24-chose--coroutine-based-socket-or-asynchronous-socketchannel-or-thread-pool-for-slow-io-operations) to get more details.
Hope this blog [Inside NGINX: How We Designed for Performance & Scale](https://www.nginx.com/blog/inside-nginx-how-we-designed-for-performance-scale/) be helpful to understand the I/O mode of NGINX. 

BTW if you want to discuss this issue by Chinese please contact me by email.
