### ISSUE TITLE
not working @ macosx

### ISSUE THREAD

**Issue by ryanjin** [nginx-clojure/nginx-clojure#112]
> 2016-04-01 22:15:50.328 nginx-macosx[7910:1036829] The application with bundle ID (null) is running setugid(), which is not allowed.
> 2016/04/01 22:15:50 [error] 7911#0: jvm may be mad for wrong options! See hs_err_pid****.log for detail! restarted 2
> 2016/04/01 22:15:50 [alert] 6054#0: worker process 7911 exited with fatal code 2 and cannot be respawned

**Comment by xfeep** [comment]
@ryanjin Please try 

```nginx
## in nginx.conf
http {
  
   jvm_classpath_check off;


}
```

**Comment by ryanjin** [comment]
i will try, thnks

**Comment by gzeureka** [comment]
I'm using OSX and JDK 1.8
nginx.conf:
jvm_path  /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/server/libjvm.dylib

logs/error.log
No Java runtime present, requesting install.
2016/04/20 23:20:35 [error] 24901#0: jvm may be mad for wrong options! See hs_err_pid****.log for detail! restarted 2
2016/04/20 23:20:35 [alert] 24894#0: worker process 24901 exited with fatal code 2 and cannot be respawned
2016/04/20 23:21:25 [notice] 24935#0: signal process started

**Comment by xfeep** [comment]
What the output about the command "java -version"

The error message "No Java runtime present, requesting install."  seems jdk
8 was not installed correctly.

**Comment by gzeureka** [comment]
java -version output:

java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

**Comment by xfeep** [comment]
It is a bug about JNI of jdk on macosx and its link is http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7131356 
Please try the steps from http://stackoverflow.com/questions/19563766/eclipse-kepler-for-os-x-mavericks-request-java-se-6/19594116#19594116

**Comment by gzeureka** [comment]
Thanks a lot! It works.

**Comment by xfeep** [comment]
@gzeureka You're  welcome!

**Comment by yegor86** [comment]
Hi @xfeep, 
I have this issue when running nginx-closure on fresh vm (Red Hat Enterprise Linux 7.3)
JDK version: jdk-8u131-linux-x64(RPM)

Adding `jvm_classpath_check off;` variable did not help me to address this issue

**Comment by goprag** [comment]
nginx-clojure-0.4.3.jar
on Red Hat 4.8.5-11
Have set jvm_classpath_check off;
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-b16)

Still having issue:
jvm may be mad for wrong options! See hs_err_pid****.log for detail! restarted 2
worker process 16517 exited with fatal code 2 and cannot be respawned

Any suggestion?
