### ISSUE TITLE
logging fail @centos 6.5

### ISSUE THREAD

**Issue by ryanjin** [nginx-clojure/nginx-clojure#113]
i use slf4j+logback, here is the logback.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration scan="true" scanPeriod="10 seconds">

<appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
      <fileNamePattern>logs/router.%d{yyyy-MM-dd}.log</fileNamePattern>
      <maxHistory>30</maxHistory>
    </rollingPolicy>

    <encoder>
      <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %-10contextName %logger{36} - %msg%n</pattern>
    </encoder>
  </appender>
 <root level="debug">
        <appender-ref ref="FILE"/>
    </root>
</configuration>
```

but logs/router.xxx.log could not be found at my server. 

Does something i missed? @xfeep

**Comment by xfeep** [comment]
@ryanjin Please make sure logback.xml can be found in the classpath.
e.g. Suppose the path of logback.xml is  `/opt/test/logcfg/logback.xml` and in nginx.conf

```nginx

http {

  jvm_classpath '/opt/test/logcfg:other-classpath...';
}

```

**Comment by xfeep** [comment]
@ryanjin  Is there any progress? 
If nginx worker processes have no write permission about logs/router.*.log or have no access permission about logback.xml,  log files won't be created.
