### ISSUE TITLE
alert need jdk 1.6 on mac os

### ISSUE THREAD

**Issue by huaoguo** [nginx-clojure/nginx-clojure#117]
jvm_path /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/server/libjvm.dylib;

When I run ./nginx-macos, the system alert me to download a jdk 1.6

**Comment by xfeep** [comment]
This issue is the same with issue #112 
It is a bug about JNI of jdk on macosx and its link is http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7131356 
Please try the steps from http://stackoverflow.com/questions/19563766/eclipse-kepler-for-os-x-mavericks-request-java-se-6/19594116#19594116

**Comment by huaoguo** [comment]
thanks

**Comment by xfeep** [comment]
@huaoguo 
Not at all. Have you resolved it?
