### ISSUE TITLE
Support for NginX 1.9

### ISSUE THREAD

**Issue by scaratec** [nginx-clojure/nginx-clojure#119]
Hi y'all!

I'm planning a new project and I'm wondering if I can use NginX 1.9 für NginX-Clojure. I'm already using NginX-Clojure in other project and I'm happy with it.

Qustion: Will there be a support for NginX 1.9 in the near future?

**Comment by xfeep** [comment]
@scaratec 
I think it should work with NginX 1.9 and NginX 1.10.
I will test it if I have time. Please let me know if there's any issue with  NginX 1.9 or NginX 1.10.
