### ISSUE TITLE
Segfault when there is no http block

### ISSUE THREAD

**Issue by LinuxJedi** [nginx-clojure/nginx-clojure#123]
When there is no http block in the configuration and nginx-clojure is compiled in NGINX will segfault on startup. An example of this is if someone is using their NGINX binary just for stream.

The segfault is on ngx_http_clojure_module.c:897

``` c
ngx_http_clojure_main_conf_t *mcf = ctx->main_conf[ngx_http_clojure_module.ctx_index];
```

**Comment by xfeep** [comment]
@LinuxJedi Thank you! I'll review your PR soon.
