### ISSUE TITLE
Integration with Nginx commercial version

### ISSUE THREAD

**Issue by AshwinJay** [nginx-clojure/nginx-clojure#125]
Hello, is it possible to get nginx-clojure to work against the commercial Nginx version? There are some features like DNS resolution and backend connection caching that would make it a powerful combination.

Since the modules have to be added at compile time, I'm guessing no?

Thanks.

**Comment by xfeep** [comment]
With PR #120 we can compile nginx-clojure to a dynamic module. Because NGINX Plus R9 supports dynamic modules, it's possible to get  nginx-clojure to work against NGINX Plus R9+.
