### ISSUE TITLE
nginx proxying and nginx-clojure custom business logic

### ISSUE THREAD

**Issue by Artgit** [nginx-clojure/nginx-clojure#126]
I need to proxy all user request from user to domain A -> to external domain B.

Also I need to introduce some custom business logic while proxying from A to B.

One of the task for this custom business logic - I need to process HTML on the fly and for example replace in HTML all links from domain B to A. Also, I need to proxy HTTP cookies and I need to implement content targeting based on different conditions. 

I'm a Java developer so I'm primarily interested in this language.

Is it possible with nginx and nginx-clojure ?

**Comment by xfeep** [comment]
It's possible.
A rewrite handler can be used to change proxy target.
A body filter can be used to change the response body from upstream sever/content handler.
A header filter can be used to change response headers  from upstream sever/content handler.
Nginx built-in directives such as `proxy_set_header`, `proxy_pass_header`, `proxy_cookie_domain` etc should be useful too.

**Comment by Artgit** [comment]
Thanks!
