### ISSUE TITLE
Can't access environment variable in NginxJavaRingHandler

### ISSUE THREAD

**Issue by ashvin-kanani-dev** [nginx-clojure/nginx-clojure#127]
I deployed nginx-clojure as docker container.

I run nginx from docker file using command `CMD ["./nginx", "-g", "daemon off;"]`

I have set some environment variable when building docker image for nginx-clojure.
Sample Dockerfile is

```
FROM java:8
COPY /home/user1/nginx-clojure/ /etc/nginx-clojure/
COPY /home/user1/libs/*.jar /etc/nginx-clojure/libs/
ENV TEST_ENV1 test
WORKDIR "/etc/nginx-clojure"
CMD ["./nginx", "-g", "daemon off;"]
```
I have created Java ring handler and is a part of class path.
I have some logic to use environment variable in ring handler to perform proxy pass.
But, I am not able to access the environment variable I set (TEST_ENV1) using syntax below in my Java ring handler.

```
System.getenv("TEST_ENV1");
```

To test whether the process starting nginx-clojure is able to read environment variable, I have updated my CMD in my `Dockerfile`

```
...
CMD ["sh", "run.sh"]
```

run.sh

```
echo $TEST_ENV1 >> test.txt
./nginx -g "daemon off;"
```
It appends actual value to `test.txt` but again not able to read it in ring handler.

Then I tried to access process tree and found nginx worker process is child of nginx and nginx is run from run.sh. So, as per my guess all child processes should able to read environment variable a parent process is able to read.

pstree -a
```
sh run.sh
  └─nginx
      └─nginx 
          └─8*[{nginx}]

```

Can any one help me to resolve my issue?

**Comment by xfeep** [comment]
Please add below in nginx.conf

```nginx
env TEST_ENV1;
```

More details can be found at http://nginx.org/en/docs/ngx_core_module.html#env

**Comment by ashvin-kanani-dev** [comment]
Thanks a lot. It worked for me.
