### ISSUE TITLE
nginx add-module: run ./configure, show "javac not found, please put it in your PATH" by check jdk

### ISSUE THREAD

**Issue by Chocolate1949** [nginx-clojure/nginx-clojure#128]
nginx-clojure/src/c/config   line 40 ：
_##check jdk
if ! type javac; then
	echo "javac not found, please put it in your PATH"_

I check jdk, PATH & CLASSPATH is ok, and command "sh /nginx-clojure/src/c/config" , it work;
	but run command "
sudo ./configure --prefix=/usr/local/nginx  --add-module=/home/nginx-clojure-0.4.4/src/c",
it show like "
 + ngx_http_rds_csv_filter_module was configured  
adding module in /home/nginx-clojure-0.4.4/src/c  
/home/nginx-clojure-0.4.4/src/c/config: line 29: type: javac: not found  
**javac not found, please put it in your PATH**  "
I don't understand the deep principles of add-module, please tell me why about this ERROR tips.
thanks.

**Comment by xfeep** [comment]
When run sudo the $PATH is different from the one of a non-root user. e.g.

```shell
$ echo "echo \$PATH" > p.sh
$ sh p.sh
/home/who/bin:/opt/texbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$ sudo sh p.sh
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

In the most cases we need not run ./configure with sudo, these below steps are enough. 

```shell
### configure arguments are omitted here
./configure
make -j
sudo make install
```

**Comment by Chocolate1949** [comment]
yes, You are smart . I thought it was about rights issue of linux, I had taken a long time to resolve this problem yesterday, I did it by other means ; However, Your thinking is the just best one. 
THX.

**Comment by xfeep** [comment]
You're welcome!
