### ISSUE TITLE
external groovy handler does not work, inlined code does

### ISSUE THREAD

**Issue by vkonnyu** [nginx-clojure/nginx-clojure#131]
I'm trying to make the HelloGroovy example work with version 0.4.4. and groovy-all 2.4.5
https://groups.google.com/forum/#!topic/groovy-user/8pR5lMVbIw8

When I'm inlining the code in nginx.conf, it works nicely, however when I'm trying to move it to its external file it does not. I thought it might not gets picked up and put it different places in the openresty directory, even compiled with groovyc and put it in a jar besides the groovy/nginx/clojure jars but it does not seem to help. Any pointers what should I do?

error.log
2016/07/25 18:07:27 [notice] 2970#0: signal process started

**Comment by xfeep** [comment]
I think it was caused by classpath.  Suppose your groovy file is HelloGroovy.groovy and its content is

```groovy
package mytest;

import nginx.clojure.java.NginxJavaRingHandler;
import java.util.Map;

public class HelloGroovy implements NginxJavaRingHandler {
    public Object[] invoke(Map<String, Object> request){
       return [200, ["Content-Type":"text/html"], "Hello, Groovy & Nginx!"];
    }
 }
```
Because its package is `mytest` so `HelloGroovy.groovy` must be put into a directory named `mytest`. Suppose the full path of `HelloGroovy.groovy` is `/opt/one/mytest/HelloGroovy.groovy`, path `/opt/one` must be in the classpath defined by directive `jvm_classpath`. e.g.

```nginx
jvm_classpath '/opt/one:other-classpath-xxx';
```
Note that we also must make the nginx worker process have enough permission to access HelloGroovy.groovy and all directories in its path.

```shell
## list all nginx process and see the user of nginx worker processes
$ ps uax | grep nginx
```

**Comment by vkonnyu** [comment]
thanks for the help, realy appreciated. It seems I had multiple problems in my setup. Just noticed the worker processes use a different user, changed it to root for the time being, and also changed permissions on the folders to 777.

now I have
/opt/mytest/HelloGroovy.groovy  //with the same content

in openresty root folder
>ls libs/
groovy-all-2.4.5.jar  nginx-clojure-0.4.4.jar

in nginx.conf:
user root;
...
jvm_path '/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server/libjvm.so';
jvm_classpath 'libs/*:/opt';
...
location /groovy {
     content_handler_type 'groovy';
     content_handler_code 'mytest.HelloGroovy';
}

> sudo ./nginx/sbin/nginx

now error.log says
2016/07/26 14:34:15 [notice] 8260#0: signal process started
Exception in thread "main" java.lang.ClassCastException: script14695364555932023551408 cannot be cast to nginx.clojure.java.NginxJavaRingHandler
	at nginx.clojure.groovy.NginxGroovyHandlerFactory.newInstance(NginxGroovyHandlerFactory.java:47)
	at nginx.clojure.NginxHandlerFactory.fetchHandler(NginxHandlerFactory.java:46)
	at nginx.clojure.NginxClojureRT.registerCode(NginxClojureRT.java:858)
2016/07/26 14:34:15 [error] 8261#0: invalid groovy content_handler code : mytest.HelloGroovy
2016/07/26 14:34:16 [alert] 6098#0: worker process 8261 exited with fatal code 2 and cannot be respawned

I have compiled openresty 1.9.15 with the clojure module master head checked out on Debian 8 x64

**Comment by xfeep** [comment]
Please try to replace `content_handler_code` with `content_handler_name`.
BTW, It's not a good choice to use root to run nginx worker process.

**Comment by vkonnyu** [comment]
yep, spot on, I forgot to change it. Now everything works fine, thank you very much!
>BTW, It's not a good choice to use root to run nginx worker process.
I guess permissions was the original problem, needed to be sure.
