### ISSUE TITLE
about the  jmx

### ISSUE THREAD

**Issue by 3thinkthendoit** [nginx-clojure/nginx-clojure#135]
my nginx.conf like this:
`-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=10086 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=192.1.1.100";` 

restart the nginx ,but I can't find the port 10086. How can I config?

**Comment by xfeep** [comment]
please try

```nginx
    jvm_options -Dcom.sun.management.jmxremote; 
    jvm_options -Dcom.sun.management.jmxremote.port=10086;
    jvm_options -Dcom.sun.management.jmxremote.ssl=false;
    jvm_options -Dcom.sun.management.jmxremote.authenticate=false;
    jvm_options -Djava.rmi.server.hostname=127.0.0.1;
```

**Comment by xfeep** [comment]
Note that if you have more than one nginx worker process , e.g.

```nginx
worker_processes  8;
```
The below configuration
```
jvm_options -Dcom.sun.management.jmxremote.port=10086;
```
will let only one worker process listen at 10086 and others will fail.
So in this case we can try to use built-in variable `pno` which starts at 1, e.g.

```
jvm_options "-Dcom.sun.management.jmxremote.port=1008#{pno}";
```

**Comment by 3thinkthendoit** [comment]
Ok,I get it  thank you!
