### ISSUE TITLE
Filtering web socket data

### ISSUE THREAD

**Issue by dennus** [nginx-clojure/nginx-clojure#141]
Hello! Does anybody knows, how intercept data which transmitting between WebSocket client and server, when NginxJavaHandler using as proxy?

**Comment by xfeep** [comment]
There's no direct way to do it because nginx-clojure supports neither websocket filter nor websocket client.
We may try to use [nginx-clojure server side websocket](http://nginx-clojure.github.io/more.html#38--sever-side-websocket) + third party websocket client to implement a websocket proxy.
