### ISSUE TITLE
NGX_HAVE_SHA1 not exists in current version on Nginx 

### ISSUE THREAD

**Issue by dennus** [nginx-clojure/nginx-clojure#142]
Hello!

Commit nginx/nginx@c60b61a removed non-internal SHA1 implementations, removing also "NGX_HAVE_SHA1", but now i'm receiving error message:
 nginx-clojure websocket support need SHA1 enabled

**Comment by xfeep** [comment]
Please try again with commit 1f9ec02.

**Comment by dennus** [comment]
Thanks, problem was solved.
