### ISSUE TITLE
 can't run binary file on ubuntu

### ISSUE THREAD

**Issue by prasadnadendla** [nginx-clojure/nginx-clojure#143]
I am trying to execute binary file (nginx-linux-x64) on Ubuntu. Getting the following exception
**/bin/sh: ./nginx: No such file or directory
The command '/bin/sh -c ./nginx' returned a non-zero code: 127**

Trying to run on Alpine linux and CentOS. Facing the same issue. Please let me know the issue

**Comment by xfeep** [comment]
nginx-linux-x64 can work on 64-bit ubuntu/centos, but not 32-bit OS.
please show us the output of these commands:

```shell
cd $nginx-clojure-path
ldd nginx-clojure-x64
```

**Comment by prasadnadendla** [comment]
I'm using 64 bit Ubuntu .From the below log one point which i understood that when i was trying to run binary file its throwing libjpeg.so.62 not found.... I think i might need to install that. But i don't know exact package name and version of this.

Here the output of second command
 linux-vdso.so.1 =>  (0x00007ffe7f1b1000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbe2ebc7000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fbe2e98e000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbe2e78a000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbe2e484000)
        libjpeg.so.62 => not found
        libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fbe2e25e000)
        libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fbe2dfbb000)
        libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fbe2dd7f000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbe2d9ba000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbe2ede5000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fbe2d7a1000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fbe2d577000)

**Comment by prasadnadendla** [comment]
I tried installing libjpeg62 with the below command.But getting the following error message
sudo apt-get install  libjpeg62

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libjpeg62
The command '/bin/sh -c apt-get install ca-certificates openssl bash libjpeg62' returned a non-zero code: 100

**Comment by prasadnadendla** [comment]
Thank you. Issue fixed. I downloaded debian package from ubuntu site and installed package. Another ssl issue raised, but opened in another thread
