### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by prasadnadendla** [nginx-clojure/nginx-clojure#144]
I'm installing Clojure(0.4.4) from source and Nginx version is 1.10.1. I'm facing SSL issue. Can you please let me know the issue.Here the log messages
2016/11/20 14:11:21 [notice] 19#0: ngx clojure: init pipe for jvm worker, fds: 7, 8
2016/11/20 14:11:21 [notice] 19#0: ngx clojure: init pipe for jvm worker, fds: 7, 8
2016/11/20 14:16:23 [info] 19#0: *1 peer closed connection in SSL handshake (32: Broken pipe) while SSL handshaking, client: 10.128.38.160, server: 0.0.0.0:443
2016/11/20 14:16:25 [info] 19#0: *2 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking, client: 10.128.38.160, server: 0.0.0.0:443
2016/11/20 14:16:35 [info] 19#0: *3 peer closed connection in SSL handshake (104: Connection reset by peer) while SSL handshaking, client: 10.128.38.160, server: 0.0.0.0:443

**Comment by xfeep** [comment]
I don't think it is related to nginx-clojure.
The message means SSL handshake failed. It can be caused by bad/expired x509 certificate or wrong host name which doesn't match the host name from the x509 certificate.
