### ISSUE TITLE
Handler for logging response info

### ISSUE THREAD

**Issue by drewr** [nginx-clojure/nginx-clojure#150]
nginx-clojure is great!  We at Elastic are building on top of it and it's been pleasant (and fast!).

Like [this person](https://groups.google.com/d/msg/nginx-clojure/2Oz5cPBcPFM/rHn9mUEqxLMJ), we need to log response from Clojure.  We have a header filter where we log to Elasticsearch, but we really need to be able to capture info later in the request cycle, around the time nginx would log to access log.

I didn't see an issue opened already, so I thought I'd record the request.  Is this even possible?

**Comment by xfeep** [comment]
Please try [body filter](http://nginx-clojure.github.io/configuration.html#28-nginx-body-filter).

**Comment by drewr** [comment]
The two things I'd like to log are:

1. The size of the response body
1. The status code

The body filter doesn't seem to do what I need.  In order to count the bytes of the body, I need to maintain state between calls to the handler.  Also, because I'm proxying binary data, I also need something other than a string for the chunks.

What I imagine would serve this purpose is something like a "post filter" which would give me a response object that I can read right before it gets sent back to the client.

**Comment by xfeep** [comment]
The clojure API of nginx-clojure only supports string body but we can use java body handler to handle binary body.
BTW I think java/clojure log handlers  are the best in your case BUT we have not supported them yet.

**Comment by mengzheng** [comment]
>> BTW I think java/clojure log handlers are the best in your case BUT we have not supported them yet.

In my project, I also need to pipe access log information to backend for accounting purpose. Do we support the java/closure log handlers now? If not, do you have plan to support it in near future?

**Comment by xfeep** [comment]
v0.5.0 supports [log handler](https://nginx-clojure.github.io/configuration.html#user-content-29-nginx-log-handler)
