### ISSUE TITLE
I get an error for the external handler

### ISSUE THREAD

**Issue by id042013** [nginx-clojure/nginx-clojure#154]
I'd appreciate a little help to make this work. First, I'd like to say that I managed to get it working with the inline handler, so my setting should be ok.

But I could not get the external handler to work and I get an error telling the code is invalid.

I have the following setup:

;nginx.conf
`jvm_classpath "libs/*:jars/nginx-clojure-0.4.4.jar";`

1. First I tried to use a single file (no app project)

```
;nginx.conf
location /myclojure {
    content_handler_type clojure;
    content_handler_name 'core/hello-world';
    }
```

```
;libs/core.clj
;https://nginx-clojure.github.io/directives.html#content_handler_name
(ns core
  (:gen-class))

(defn hello-world [request]
    {:status 200,
     :headers {"Content-Type" "text/plain",
     :body "hello world"})
```

2. Secondly I tried to create a project
```
cd libs
lein new app example
;libs/example/src/example/core.clj
; I added the same code as in the first example
```

```
;nginx.conf
; changed the following line to
content_handler_name 'example.src.example.core/hello-world'
```

**Comment by xfeep** [comment]
Hi,

Please try

jvm_classpath libs/*:jars/nginx-clojure-0.4.4.jar:libs/example/src/

content_handler_name 'example.core/hello-world'


Another way is to run "lein uberjar" to get a self-contained jar file and
then put it in the jvm_classpath.

Regards.
xfeep

**Comment by id042013** [comment]
Many thanks xfeep, solved, issue may be closed now.
