### ISSUE TITLE
Body filter not changed response state after proxy pass

### ISSUE THREAD

**Issue by dennus** [nginx-clojure/nginx-clojure#155]
I'm trying to use body filter after proxy pass for change response body and return response state code basing on response data. But when when I returning from invoke method, response state looks unchanged(if upstream returned 200, i can't change to 403, for e.g.).

**Comment by xfeep** [comment]
Typically status code can be changed by header filter.Body filter runs after header filter. It's too late to change status code in body filter because header filter has sent it already.
In your case we should suspend header sending until we compute the status code by response body so that you can control both response status and body by your body filter. Here is an example.

```nginx
location /mytest {
  header_filter_type java;
  header_filter_name filter.ResponseFilter;
  content_filter_type java;
  content_filter_name filter.ResponseFilter;
}
```

```java
package filter;

import java.io.IOException;
import java.io.InputStream;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import nginx.clojure.ChannelCloseAdapter;
import nginx.clojure.NginxClojureRT;
import nginx.clojure.java.NginxJavaBodyFilter;
import nginx.clojure.java.NginxJavaFilterRequest;
import nginx.clojure.java.NginxJavaHeaderFilter;
import nginx.clojure.java.NginxJavaRequest;

public class ResponseFilter implements NginxJavaHeaderFilter, NginxJavaBodyFilter {

	static Map<Long, NginxJavaFilterRequest> headerFilterRequests = new ConcurrentHashMap<Long, NginxJavaFilterRequest>();
	
	public ResponseFilter() {
	}

	@Override
	public Object[] doFilter(Map<String, Object> request, InputStream bodyChunk, boolean isLast) throws IOException {
		long nr = ((NginxJavaRequest)request).nativeRequest();
		NginxJavaFilterRequest fr = headerFilterRequests.remove(nr);
		
		if (fr != null) {
			fr.responseStatus(403); // change status code
			NginxClojureRT.ngx_http_filter_continue_next(nr, -1); //continue next header filter
		}
		
		if (!isLast) {
			//store body here
		}else {
                        //send the new whole body
			return new Object[] {403, null, new-body};
		}
	}

	@Override
	public Object[] doFilter(int status, Map<String, Object> request, Map<String, Object> responseHeaders)
			throws IOException {
		NginxJavaFilterRequest fr = (NginxJavaFilterRequest)request;
		fr.hijack(false); //suspend header sending
		responseHeaders.remove("Content-Length");
		headerFilterRequests.put(fr.nativeRequest(), fr);
		fr.addListener(fr.nativeRequest(), new ChannelCloseAdapter<Long>(){
			@Override
			public void onClose(Long data) throws IOException {
				headerFilterRequests.remove(data);
			}
		});
		return null;
	}

}

```

**Comment by dennus** [comment]
I tried this sample, but it does work correctly - it first request (sometimes 2 or more) attempt that's allright. But after series request Nginx stop response. In my log file I see that all was done and error not reported.

**Comment by xfeep** [comment]
@dennus Could you please show us your Nginx version and nginx-clojure version?

**Comment by dennus** [comment]
I'm use nginx 1.11.2 and nginx-clojure version 0.4.4 (checkout from master)

**Comment by xfeep** [comment]
@dennus Please try to add `ngx_http_finalize_request(nr, rc);` after `ngx_http_filter_continue_next(nr, -1);`, e.g.

```java
            long rc = NginxClojureRT.ngx_http_filter_continue_next(nr, -1); //continue next header filter
	    NginxClojureRT.ngx_http_finalize_request(nr, rc); //for hijacked request
```

**Comment by dennus** [comment]
Thank's. All working.

**Comment by novakg** [comment]
Hi Guys,
I'm trying to do something similar: concatenate the whole body from the proxy response chunks and then do a transformation on the whole body and return that to the caller. My questions is: what do you exactly do in the 
`	if (!isLast) {
			//store body here
		}`
block, what does the method return in that case?
If I return the `bodyChunk`, then each chunk will be sent to the caller immediately as far as I can see.

**Comment by xfeep** [comment]
@novakg Please try 
```java
return new Object[] {null, null, null};
```
