### ISSUE TITLE
On MacOSX thread pool mode doesn't work with Nginx 1.10.2+

### ISSUE THREAD

**Issue by knasim** [nginx-clojure/nginx-clojure#156]
I'm seeing the following all over my in my nginx error.log file.     And the file size grows very quickly.
built nginx-clojure module.  nginx version is 1.11.6

2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)
2017/01/17 11:59:58 [alert] 92272#0: kevent() failed (22: Invalid argument)

**Comment by xfeep** [comment]
ngx_kqueue_set_event failed by a invalid flag. Do you run nginx on freebsd-like OS? Could you please show us your nginx.conf? It is better that turn on debug log e.g.
```
error_log  logs/error.log debug;
```

After restart/reload nginx  we'll get more detail log.

**Comment by knasim** [comment]
@xfeep thanks .
Yes for my local environment I am running nginx on macOS (sierra).

Ok - Let me turn on debug on error log and then I'll post back.

**Comment by knasim** [comment]
with debug log turned on not much - this is what i'm seeing:

2017/01/17 15:06:46 [info] 94550#0: *1 kevent() reported that client 127.0.0.1 closed keepalive connection
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)
2017/01/17 15:06:46 [alert] 94550#0: kevent() failed (22: Invalid argument)

**Comment by knasim** [comment]
might be a memory leak with nginx.   i couldn't reproduce the issue on linux.

**Comment by xfeep** [comment]
@knasim 
It seems Nginx doesn't work well with kqueue on MacOSX.
Do you set event module to kqueue? e.g.
```nginx
events {
    use kqueue;
    ....
}
```

If so please change it to  
```nginx
events {
    # use select module for dev usage because it may hurts performance in product env 
    use select; 
    ....
}
```

**Comment by knasim** [comment]
@xfeep - thanks for getting back to me.  Maybe we should raise this with nginx.  And the behavior is strange.  It starts writing very fast to the error.log filling it up so quickly that you're disk space is almost entirely used up.  Mine went to up 200G.

i'll try with events.

**Comment by knasim** [comment]
kqueue - the effective method, used on FreeBSD 4.1+, OpenBSD 2.9+, NetBSD 2.0 and MacOS X. With dual-processor machines running MacOS X using kqueue can lead to kernel panic.

**Comment by knasim** [comment]
So tried it with "select"  still the same


2017/01/18 17:52:20 [alert] 29653#0: select() failed (22: Invalid argument)
2017/01/18 17:52:20 [alert] 29653#0: select() failed (22: Invalid argument)
2017/01/18 17:52:20 [alert] 29653#0: select() failed (22: Invalid argument)
2017/01/18 17:52:20 [alert] 29653#0: select() failed (22: Invalid argument)
2017/01/18 17:52:20 [alert] 29653#0: select() failed (22: Invalid argument)
2017/01/18 17:52:20 [alert] 29653#0: select() failed (22: Invalid argument)
2017/01/18 17:52:20 [alert] 29653#0: select() failed (22: Invalid argument)
2017/01/18 17:52:20 [alert] 29653#0: select() failed (22: Invalid argument)
2017/01/18 17:52:20 [alert] 29653#0: select() failed (22: Invalid argument)
2017/01/18 17:52:20 [alert] 29653#0: select() failed (22: Invalid argument)
2017/01/18 17:52:20 [alert] 29653#0: select() failed (22: Invalid argument)
2017/01/18 17:52:20 [alert] 29653#0: select() failed (22: Invalid argument)
2017/01/18 17:52:20 [alert] 29653#0: select() failed (22: Invalid argument)
2017/01/18 17:52:20 [alert] 29653#0: select() failed (22: Invalid argument)
2017/01/18 17:52:20 [alert] 29653#0: select() failed (22: Invalid argument)
2017/01/18 17:52:20 [alert] 29653#0: select() failed (22: Invalid argument)
2017/01/18 17:52:20 [alert] 29653#0: select() failed (22: Invalid argument)

**Comment by xfeep** [comment]
@knasim Does this only happen with nginx-clojure or still happen if nginx-clojure is disabled?

**Comment by knasim** [comment]
@xfeep  - it happens with nginx-clojure.  do you have OSX ?  Try it - and you should be able to reproduce the issue.   my version of nginx is 1.11.6 which I build from source using make utility.

**Comment by xfeep** [comment]
@knasim Yes on mac osx it happens with nginx 1.11.6/nginx 1.10.2 + nginx-clojure but it doesn't happen with nginx 1.8.0 + nginx-clojure.

**Comment by xfeep** [comment]
@knasim Thread pool mode doesn't work. But default mode is OK.

**Comment by xfeep** [comment]
@knasim Commit a07ac97 fixed it. Please try again.

**Comment by knasim** [comment]
@xfeep  - glad to see you were able to reproduce the issue.   I shall pull your commit and verify that bug has been resolved.   kudos to me for finding bug 👍

**Comment by azadianDevelopers** [comment]
I had exactly the same issue
It turned out to be this line that was causing the isue in my nginx location config...

proxy_read_timeout 999999999
