### ISSUE TITLE
how to control nginx log from rewrite handler

### ISSUE THREAD

**Issue by knasim** [nginx-clojure/nginx-clojure#158]
@xfeep  - i'd like to know how i can write to one of my nginx log files from within a rewrite_handler or content_handler.  Is it possible to call a nginx directive from nginx-clojure ?

**Comment by xfeep** [comment]
Nginx directive can not be invoked. But we can set nginx variables to afffect  their execitions.

**Comment by knasim** [comment]
ok thanks.  it would be a neat feature to have - although i'm not sure how difficult that would be.
