### ISSUE TITLE
nginx -s reload doesn't start new JVM's if the JVM has a bound port

### ISSUE THREAD

**Issue by alex-sherwin** [nginx-clojure/nginx-clojure#159]
Tested on `nginx-clojure-0.4.3` and `nginx-clojure-0.4.4` against `nginx-1.10.1` and `nginx-1.10.3`

If the JVM is configured with any bound ports (common examples being debug port or JMX port), when I run `nginx -s reload`, what happens is the existing worker processes are shut down but no new ones are started.

At this point making HTTP requests to nginx hangs because there are no live worker processes

If you then run `nginx -s reload` again, the worker processes will come back.

I presume this is because the initial reload tries to start new JVMs before the others have actually exited, and the JVM's probably just fail to start due to port binding conflicts.

I don't know if there's a way around this, because as I understand it, nginx will keep the old worker processes alive for some amount of time to process live requests, and startup new worker processes to handle new requests.  Which means there would be no way to avoid this conflict.

If my assumptions are correct, there might be nothing to do here for nginx-clojure, except maybe add some notes to the documentation to draw attention to this scenario

Thanks for making a great nginx plugin!

**Comment by xfeep** [comment]
Thank you for this good reminder!
BTW If the bound port is  binded by our java code we can use socket option SO_REUSEADDR to avoid this issue, e.g.
```java
serverSocket.setReuseAddress(true);
```

**Comment by alex-sherwin** [comment]
Thanks for that, I think it'd be possible to do something like this for JMX by creating your own socket factory for the MBean server

But I don't think that there's a way you could setup SO_REUSEADDR for the JVM debug options that I can see.  Not a huge deal though, as the debug port should hopefully only be being used in dev scenarios where you'd know it was necessary to run `nginx -s reload` twice
