### ISSUE TITLE
Can content handler persistently connect to http2 server?

### ISSUE THREAD

**Issue by dfeng99** [nginx-clojure/nginx-clojure#161]
Hi there,

I build a nginx-clojure server with http2 support, I plan to implement an external java content handler which persistently connect to a http2 server and collect messages whenever it receives from the web clients then push it to the http2 server. 
I understand that nginx-clojure supports webSocket and long polling & SSE go through NginxHttpServerChannel, how about http2? 

Thanks & regards

**Comment by xfeep** [comment]
NginxHttpServerChannel has not supported http2 yet.

**Comment by dfeng99** [comment]
Thanks anyway! this project is amazing!

**Comment by dfeng99** [comment]
After explore, I change the scenario by collecting message from web client through whatever method  that Nginx-clojure supported then push the message to another server by calling java http2 library and it works! It then bypass the server channel. I believe there are still ways to leverage Nginx native http2 capability to have full http2 tunnel from the web client to the backend server, isn't it?

**Comment by zaid-saeedi-khan** [comment]
Hi,
Does nginx-clojure-0.4.5 support http2? I am getting following error when enabling it on windows 10:

the "http2" parameter requires ngx_http_v2_module in D:\zaid\ProgramFiles_\nginx-clojure-0.4.5/conf/nginx.conf
