### ISSUE TITLE
Sending multiple request using asyn socket

### ISSUE THREAD

**Issue by dennus** [nginx-clojure/nginx-clojure#162]
Hello! Can you describe, how to send multiple request using asyn socket. In the given example  [https://github.com/nginx-clojure/nginx-clojure/blob/ec59f73b712010c05700bd7e906815759e8665b0/test/java/nginx/clojure/net/SimpleHandler4TestNginxClojureAsynSocket.java](url) handler sends one request and after receive  response connection closing. Can you give some explanation, how to send multiple request without closing upstream channel?

And second question - how to access native websocket  data in the  ChannelListener object (non-decoded Websocket frame)?

**Comment by xfeep** [comment]
1. for the first question about AsynSocket

In the example we send header `Connection: close` to tell upstream server that we want it close the connection after the response completes.If we want to send multiple requests we need send header `Connection:Keep-Alive` and do not close the connection until all responses return.

2. for the second question about raw websocket message

We can use NginxHttpServerChannel.turnOnEventHandler to make our listener have a chance to handle all raw messages. Please note that neither  NginxHttpServerChannel.webSocketUpgrade nor nginx directive auto_upgrade_ws should be used. e.g.

```java
        NginxRequest req = (NginxRequest) request;
        NginxHttpServerChannel downstream = req.hijack(true);
        downstream.turnOnEventHandler(true, true, true);
        //set context object for later usage, context object can be any java object
        downstream.setContext(context);
        // it our duty to handle websocket upgrade request now
        // e.g. downstream.send(ws-upgrade-response-here) 
        
        // add listener to handle websocket raw message
        downstream.addListener(...) //onRead & onWrite will be invoked to handle websocket raw message
```

**Comment by dennus** [comment]
When event "onWrite" take place, can I write data later (if it's empty currently). I see, that if we returning without writing data in onWrite event handler, this event never be happened again. Only onRead event  repeating (but we don't have any data to read)

**Comment by xfeep** [comment]
@dennus You can still write data later after onWrite event happens.
