### ISSUE TITLE
Permessage-Deflate incorrect working

### ISSUE THREAD

**Issue by dennus** [nginx-clojure/nginx-clojure#163]
Hello!
When websocket client send uncompressed message (with RSV1 = 0) to the channel (with accepted permessage-deflate extension) connection aborting with status code = 1006 and error log contains this message:
2017/02/28 12:04:52 [error] 20226#20226: *6 inflate error : -3 while upgraded connection, client: 10.36.7.197, server: 10.36.7.196, request: "GET /ws_stub HTTP/1.1", host: "10.36.7.196:8090"

But,  according RFC 7692, client may send uncompressed message with permessage-deflate enabled, unsetting RSV1 flag.

**Comment by xfeep** [comment]
@dennus Thanks. We 'll follow RFC 7692. But now we only support draft 27 https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-27 .

**Comment by dennus** [comment]
In Draft27,  behavior seems indentical :) : 
PMCEs use the RSV1 bit of the WebSocket frame header to indicate whether a message is compressed or not, so that an endpoint can choose not to compress messages with incompressible contents

**Comment by xfeep** [comment]
@dennus Thank you!
I really have no time to confirm or fix this issue these days. PRs would be welcome!

**Comment by xfeep** [comment]
@dennus Sorry for so late fix. Commit bd61278 should fix it but we have not found any tool to test it.
