### ISSUE TITLE
NginxClojureAsynSocket can only be operated in main thread

### ISSUE THREAD

**Issue by dennus** [nginx-clojure/nginx-clojure#164]
When tool coroutine mode enabled (I'm try to generate wave config), error "NginxClojureAsynSocket can only be operated in main thread" occurred when I call NginxClojureAsynSocket(). Does it means, that asyn sockets are  not usable in coroutine mode?

**Comment by xfeep** [comment]
NginxClojureAsynSocket can work in coroutine mode but not work in thread pool mode. When tool mode enabled thread pool will be used to make sure that nginx worker won't be blocked if there's any handler accesses services provided by the same nginx instance. We can disable thread pool by setting jvm_workers to 0 e.g. 

```
jvm_workers 0;
```
