### ISSUE TITLE
load testing nginx-clojure

### ISSUE THREAD

**Issue by knasim** [nginx-clojure/nginx-clojure#166]
Hi @xfeep 

Have there been any load tests performed on nginx-clojure.  Are there any benchmarks supporting the performance in terms of system resources, memory footprint etc.    A

Thanks,

**Comment by xfeep** [comment]
Hi @knasim 
I think it's easy to do load tests by wrk. There 's the result about a [simple load tests](https://github.com/ptaoussanis/clojure-web-server-benchmarks) 
Please follow [this link](https://github.com/ptaoussanis/clojure-web-server-benchmarks/issues/31#issuecomment-124793600) which is about memory footprint.
