### ISSUE TITLE
jmxremote

### ISSUE THREAD

**Issue by knasim** [nginx-clojure/nginx-clojure#168]
Tried to set these via jvm_options (nginx.conf) but unable to do so and worker process is not spawned

-Dcom.sun.management.jmxremote
-Dcom.sun.management.jmxremote.authenticate=true
-Dcom.sun.management.jmxremote.ssl=false 
-Dcom.sun.management.jmxremote.port=`<port#>`
-Djava.rmi.server.hostname=`<server-ip>`

It should accept them perhaps combination ?

Creates the following message in errors.log
jvm may be mad for wrong options! 

looked in /tmp and there is thread dump.

**Comment by xfeep** [comment]
jvm_options should be used once per option, e.g.

```nginx
jvm_options "-Dcom.sun.management.jmxremote";
jvm_options "-Dcom.sun.management.jmxremote.authenticate=true";
```

And if there're more than one worker processes it will fail for port conflict. nginx-clojure built-in variable `#{pno}`  can be used to resolve it, e.g,

```nginx
jvm_options "-Dcom.sun.management.jmxremote.port=100#{pno}";
```

**Comment by knasim** [comment]
@xfeep  - yes I did exactly - once per option - yet it still reports 
"jvm may be mad for wrong options!"

and i only creating single worker process. so no issue for port conflict.

**Comment by xfeep** [comment]
@knasim I have tested below configuration on ubuntu and it's ok.

```nginx
jvm_options -Dcom.sun.management.jmxremote;
jvm_options -Dcom.sun.management.jmxremote.authenticate=true;
jvm_options -Dcom.sun.management.jmxremote.ssl=false;
jvm_options -Dcom.sun.management.jmxremote.port=8444;
jvm_options -Djava.rmi.server.hostname=127.0.0.1;
jvm_options -Dcom.sun.management.jmxremote.password.file=jmx.password;
```

BTW please make sure only nginx worker process can read and write the password file.

**Comment by knasim** [comment]
@xfeep  - thanks much - i will try this.

**Comment by knasim** [comment]
@xfeep  - can you attach you're nginx file ?

**Comment by xfeep** [comment]
Here's the complete nginx-jmx.conf

```nginx

worker_processes  1;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;
    
    jvm_path auto; 
    jvm_classpath "libs/*:jars/*";
    
    jvm_options -Dcom.sun.management.jmxremote;
    jvm_options -Dcom.sun.management.jmxremote.authenticate=true;
    jvm_options -Dcom.sun.management.jmxremote.ssl=false;
    jvm_options -Dcom.sun.management.jmxremote.port=8444;
    jvm_options -Djava.rmi.server.hostname=192.168.1.5;
    jvm_options -Dcom.sun.management.jmxremote.password.file=jmx.password;

    server {
        listen       12345;
        server_name  localhost;
        location / {
            root   html;
            index  index.html index.htm;
        }
      
       error_page   500 502 503 504  /50x.html;
       
       location = /50x.html {
            root   html;
        }
        
        location /clj {
            content_handler_type clojure;
            content_handler_code '(fn[req] {:body "hello!"} )';	
	}
       
    }
}
```

**Comment by knasim** [comment]
@xfeep  - were you actually able to connect to the process using imx port 8444 ?  I don't think this works on remote JVM.  Only on local JVM

**Comment by xfeep** [comment]
@knasim Yes.

```shell
$ netstat -tulpn | grep nginx
tcp        0      0 0.0.0.0:44436           0.0.0.0:*               LISTEN      12399/nginx: worker
tcp        0      0 0.0.0.0:12345           0.0.0.0:*               LISTEN      12398/nginx-jmx.con
tcp        0      0 0.0.0.0:8444            0.0.0.0:*               LISTEN      12399/nginx: worker
tcp        0      0 0.0.0.0:34914           0.0.0.0:*               LISTEN      12399/nginx: worker

```

**Comment by knasim** [comment]
repetitively get:  jvm may be mad for wrong options! 

checked the thread dump in /tmp but no clues there.

**Comment by knasim** [comment]
@xfeep  - thanks.   what is the specs of your linux ?

I repetitively get:  jvm may be mad for wrong options! See hs_err_pid****.log for detail! restarted 2
I looked at the the thread dump as well - but couldn't find any clues.   Are quotes needed around the jvm_options (i don't think so).

**Comment by xfeep** [comment]
@knasim Quotes are not needed if there 's no special char, e.g. semicolon.
There's no specs of my linux. I have tried nginx-clojure 0.4.4 with nginx-jmx.conf on centos 5.6 and it was OK.

**Comment by kstokoz** [comment]
I also had troubles to connect when was forwarding remote port to localhost, adding following solved the issue for me  jvm_options "-Dcom.sun.management.jmxremote.rmi.port=844#{pno}";

Full set of properties:
jvm_options "-Dcom.sun.management.jmxremote";
jvm_options "-Dcom.sun.management.jmxremote.ssl=false";
jvm_options "-Dcom.sun.management.jmxremote.port=844#{pno}";
jvm_options "-Dcom.sun.management.jmxremote.rmi.port=844#{pno}";
jvm_options "-Djava.rmi.server.hostname=127.0.0.1";
jvm_options "-Dcom.sun.management.jmxremote.local.only=false";
jvm_options "-Dcom.sun.management.jmxremote.authenticate=false";
