### ISSUE TITLE
jvm creation

### ISSUE THREAD

**Issue by knasim** [nginx-clojure/nginx-clojure#169]
@xfeep  - can you please explain how this program creates JVM.  It is using JNI.
update: yes it is using JNI looking at `ngx_http_clojure_jvm.c`

**Comment by xfeep** [comment]
@knasim Just as you see ngx_http_clojure_jvm only has 135 lines where code 's simple and no secret. If you are interested in the invocation API about JNI please click this link http://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/invocation.html .

**Comment by knasim** [comment]
Thanks @xfeep - I know only 135 lines of code - but the pointers drive me nuts. 
Btw - I don't see Makefile in your code - how to perform to build ?

**Comment by xfeep** [comment]
Please see [Installation by Source](http://nginx-clojure.github.io/installation.html#12-installation-by-source) .

**Comment by knasim** [comment]
@xfeep  - Thanks !

**Comment by xfeep** [comment]
@knasim It's impossible to build nginx-clojure c code without nginx source.
