### ISSUE TITLE
Cannot add multiple Cookies in a response

### ISSUE THREAD

**Issue by jlo2177** [nginx-clojure/nginx-clojure#170]
Based on the below information from "https://github.com/ring-clojure/ring/blob/master/SPEC", it appears that multiple Headers with the same name can be added. Although, I have not been able to get this to work. I did extend ArrayMap with a Map that allows duplicate name entries (which worked), but this breaks the definition of Map. Can you explain how I should format a "seq of Strings", to add multiple Set-Cookie Headers?

:headers
  (Required, clojure.lang.IPersistentMap)
  A Clojure map of HTTP header names to header values. These values may be
  either Strings, in which case one name/value header will be sent in the
  HTTP response, or a seq of Strings, in which case a name/value header will be 
  sent for each such String value.

**Comment by xfeep** [comment]
@jlo2177 
1. If we use java the value in headers map can be a string or an array/list of strings. 
1. If we use clojure the value in headers map can be a string or a [seqs](https://clojure.org/reference/sequences) of strings.

**Comment by jlo2177** [comment]
I am coding in Java.
I attempted to use an array of Strings for the "Set-Cookie" HTTP Header (String[]). 
Then, I attempt a List (List<String>).
This did not add either of the 2 Cookies I was attempting.

**Comment by jlo2177** [comment]
When I look at the class.method NginxSimpleHandler.prepareHeaders, I do not see logic to handle a List and/or array of Strings.
I see the following (notice the comment "TODO:support another types"):

				NginxHeaderHolder pusher = fetchResponseHeaderPusher(name);
				if (pusher == RESP_CONTENT_TYPE_HOLDER) {
					if (val instanceof String) {
						contentType = (String)val;
					}else { //TODO:support another types 
						
					}
				}
				pusher.push(headers_out, pool, val);

May want to consider something like the following:

				NginxHeaderHolder pusher = fetchResponseHeaderPusher(name);
				boolean alreadyPushedValue = false;
				if (pusher == RESP_CONTENT_TYPE_HOLDER) {
					if (val instanceof String) {
						contentType = (String)val;
					} else if (val instanceof String[]) {
						// get new ResponseHeaderPusher for each value in Array
						String[] tmpVals = (String[]) val;
						boolean firstPass = true;
						for (String tmpVal: tmpVals) {
							if (!firstPass) {
								pusher = fetchResponseHeaderPusher(name);
							}
							contentType = (String)tmpVal;
							pusher.push(headers_out, pool, tmpVal);
							alreadyPushedValue = true;
						}
					} else if (val instanceof List) {
						// get new ResponseHeaderPusher for each value in List
						List tmpVals = (List) val;
						boolean firstPass = true;
						for (Object tmpVal: tmpVals) {
							if (tmpVal instanceof String) {
								if (!firstPass) {
									pusher = fetchResponseHeaderPusher(name);
								}
								contentType = (String)tmpVal;
								pusher.push(headers_out, pool, tmpVal);
								alreadyPushedValue = true;
							} else {
								//TODO:support another types 
							}
						}
					}else { //TODO:support another types 
						
					}
				}
				if (!alreadyPushedValue) {
					pusher.push(headers_out, pool, val);
				}

**Comment by xfeep** [comment]
@jlo2177 Thanks for your report this issue.
But it's nothing to do with the code you mentioned where pusher == RESP_CONTENT_TYPE_HOLDER means the current header to be handled is `Content-Type` which we have not supported array/seqs values.
Commit 61bd3a8 fixed this issue please try again.
