### ISSUE TITLE
Unable to start nginx with jvm_path auto;

### ISSUE THREAD

**Issue by prithivraj** [nginx-clojure/nginx-clojure#173]
nginx: [emerg] unknown directive "jvm_path" in /usr/local/etc/nginx/nginx.conf:28
~/Github/nginx-clojure-0.4.5  $sudo nginx -s reload
nginx: [emerg] unknown directive "jvm_path" in /usr/local/etc/nginx/nginx.conf:28

**Comment by xfeep** [comment]
Do you have another nginx instance without being compiled with nginx-clojure module?
Below commands can tell you where the default nginx is and whether it has nginx-clojure module or not. 
```shell
$ which nginx

$ nginx -V
```


If your nginx-clojure-0.4.5 is not in your PATH env varaible, please try

```shell

cd nginx-clojure-0.4.5
./nginx 

```

**Comment by fabianoamorim** [comment]
Hi I have the same issue. after executing $ which nginx, I could see it's on  /usr/sbin/nginx. With $ nginx -V I could check that nginx-clojure it's not set there , so I executed cd nginx-cloure-0.4.5 and then ./nginx. 

I open a new terminal and run $nginx -V but the nginx-clojure is not set there.
