### ISSUE TITLE
nginx-clojure pub/sub

### ISSUE THREAD

**Issue by knasim** [nginx-clojure/nginx-clojure#174]
What is the underlying messaging middleware that is used ? Or is this inter-process pub/sub ?  
Or does it use something like MQ ?

**Comment by xfeep** [comment]
pub/sub is based on nginx-clojure built-in shared map & broadcast API which is a low level, pipe based, message limited API.  e.g. 
1. when a message comes nginx-clojure will put it into a shared map first
2. nginx-clojure uses broadcast API to notify all other worker processes, viz. send a event id to them
3. all other worker processes get the event id and get the whole message from the shared map
4. nginx-clojure removes the message from the shared map.

**Comment by knasim** [comment]
@xfeep - thanks .  can you reference the code please.

**Comment by xfeep** [comment]
c source files：
- src/c/ngx_http_clojure_shared_map.c
- src/c/ngx_http_clojure_shared_map.h
- src/c/ngx_http_clojure_shared_map_hashmap.c
- src/c/ngx_http_clojure_shared_map_hashmap.h
- src/c/ngx_http_clojure_shared_map_tinymap.c
- src/c/ngx_http_clojure_shared_map_tinymap.h

java source files ：

- src/java/nginx/clojure/util/NginxSharedHashMap.java
- src/java/nginx/clojure/clj/ClojureSharedHashMap.java

Shared map is nothing to do with cluster but shared memory among one nginx master process and its several worker processes on the same computer.
