### ISSUE TITLE
jvm may be mad for wrong options!

### ISSUE THREAD

**Issue by dfeng99** [nginx-clojure/nginx-clojure#175]
Hi there,

My nginx server ran well before, today I upgrade some packages with apt-get and reboot the server and the server run into chaos. The error log shows:

2017/06/20 20:19:43 [notice] 1541#0: nginx-clojure/0.4.4
2017/06/20 20:19:45 [notice] 1665#0: using the "epoll" event method
2017/06/20 20:19:45 [notice] 1665#0: nginx-clojure/0.4.4
2017/06/20 20:19:45 [notice] 1665#0: nginx/1.10.1
2017/06/20 20:19:45 [notice] 1665#0: built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
2017/06/20 20:19:45 [notice] 1665#0: OS: Linux 4.4.0-81-generic
2017/06/20 20:19:45 [notice] 1665#0: getrlimit(RLIMIT_NOFILE): 1024:4096
2017/06/20 20:19:45 [notice] 1669#0: start worker processes
2017/06/20 20:19:45 [notice] 1669#0: start worker process 1670
2017/06/20 20:19:45 [notice] 1669#0: start worker process 1671
2017/06/20 20:19:45 [notice] 1669#0: start worker process 1672
2017/06/20 20:19:45 [notice] 1669#0: start worker process 1673
2017/06/20 20:19:51 [notice] 1669#0: signal 17 (SIGCHLD) received
2017/06/20 20:19:51 [alert] 1669#0: worker process 1672 exited on signal 11 (core dumped)
2017/06/20 20:19:51 [notice] 1669#0: start worker process 1753
2017/06/20 20:19:51 [error] 1753#0: jvm may be mad for wrong options! See hs_err_pid****.log for detail! restarted 5
2017/06/20 20:19:51 [notice] 1669#0: signal 17 (SIGCHLD) received
2017/06/20 20:19:51 [notice] 1669#0: worker process 1753 exited with code 2
2017/06/20 20:19:51 [alert] 1669#0: worker process 1753 exited with fatal code 2 and cannot be respawned
2017/06/20 20:19:51 [notice] 1669#0: signal 29 (SIGIO) received
2017/06/20 20:19:51 [notice] 1669#0: signal 29 (SIGIO) received
2017/06/20 20:19:51 [notice] 1669#0: signal 17 (SIGCHLD) received
2017/06/20 20:19:51 [alert] 1669#0: worker process 1673 exited on signal 11 (core dumped)
2017/06/20 20:19:51 [notice] 1669#0: start worker process 1754

and the server doesn't response anymore. There are too few messages to identify what's wrong with it, Can anyone help the way to debug? 

I didn't change any configuration and code and if I remarke the nginx-clojure handler in the configuration file then the nginx server can response to the request. 
I've tried to rebuild the nginx with nginx-clojure 0.4.5 but nothing help.

Here comes the java info of my environment: 
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

I've also attached with the upgraded packages list.

Regards,
David
[upgraded_packages.txt](https://github.com/nginx-clojure/nginx-clojure/files/1088223/upgraded_packages.txt)

**Comment by xfeep** [comment]
It seems JNI Invocation API can not work on Linux kernel 4.4.0-81 where JNI_CreateJavaVM will cause JVM crash.
Those versions which are not greater than 4.4.0-79 are OK.

**Comment by dfeng99** [comment]
Thanks xfeep, It back to normal when I boot from kernel 4.4.0-79.

**Comment by xfeep** [comment]
Kernel 4.4.0-83 fixed this issue. It is included in the latest ubuntu update.

**Comment by dfeng99** [comment]
Great news, thanks!
