### ISSUE TITLE
Unable to start nginx with java and nginx-clojure

### ISSUE THREAD

**Issue by rachit20** [nginx-clojure/nginx-clojure#177]
I was running nginx-1.12.0 with nginx-clojure-0.4.5 and java 8 , it was working fine but yesterday we upgraded VM OS and suddenly there was an error message while starting nginx something like "**jvm may have gone mad with wrong options , nginx cannot be re spawned**"  . In syslog i found error message as "**Jun 28 13:18:46 STREAM01A kernel: [  828.244563] nginx[5613]: segfault at 0 ip 0000000000433ff4 sp 00007ffea2e848a0 error 4 in nginx[400000+e4000]**" . After which i tried many options such as installing nginx-1.11.0 with nginx-clojure-0.4.4 and java 7 but still it failed to start . I couldn't get enough info from logs to narrow down the issue . Please help in sorting out this problem as it's a critical problem . 

nginx version: nginx/1.11.0
built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
built with OpenSSL 1.0.2g  1 Mar 2016
TLS SNI support enabled
configure arguments: --add-module=../nginx-clojure/src/c --sbin-path=/opt/nginx/bin/nginx --conf-path=/opt/nginx/conf/nginx.conf --error-log-path=/opt/nginx/logs/error.log --http-log-path=/opt/nginx/logs/access.log --pid-path=/opt/nginx/logs/nginx.pid --lock-path=/run/lock/subsys/nginx --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --with-pcre --with-debug --with-http_v2_module

**Comment by xfeep** [comment]
Do you use ubuntu? If so it 's caused by the newly linux kernel bug. Select
an older kernel should be OK.

More details can be found from these two links :

https://github.com/nginx-clojure/nginx-clojure/issues/175
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1699772

**Comment by rachit20** [comment]
Yeah I am using Ubuntu . Why this issue happened suddenly ? is it because of apt-get install or apt-get upgrade ? How can i select an older kernel version ? Could you please help with the steps to fix it ?

**Comment by xfeep** [comment]
- edit /etc/default/grub
```shell
### comment the below line
#GRUB_HIDDEN_TIMEOUT=0.
```
- run  `sudo update-grub` to apply above changes and restart

**Comment by xfeep** [comment]
Kernel 4.4.0-83 fixed this issue. It is included in the latest ubuntu update.
