### ISSUE TITLE
messaging with nginx-clojure java content handler

### ISSUE THREAD

**Issue by knasim** [nginx-clojure/nginx-clojure#178]
Hello @xfeep - I'm curious if there would be any negative impact on the NGINX workers if my java content handler is connected with a messaging broker such as Kafka.  My java content handler for each nginx request extracts some information from the request and puts this info to  a Kafka topic.  I'm wondering if this can have any negative impact on the Nginx workers ?  Such as the workers crashing too often because of this and Nginx having to restart them ?  Specifically with overhead of kafka connection creation from with each NGINX worker JVM.    Is NGINX-CLOJURE purpose just for simple request checking OR can it handle something more heavy such as putting message to a topic ?

**Comment by xfeep** [comment]
Hi @knasim , thank you for reporting this issue.
Could you please show a minimal example to reproduce this issue? e.g. try to use wrk to produce  large amounts of requests.

**Comment by knasim** [comment]
@xfeep  - it is NOT an issue.  It was a question.   Can Nginx-clojure handle something more heavy duty than simply checking the request ?   Such as after checking the request I can put a message on a queue ?

**Comment by xfeep** [comment]
Of course it can do more heavy things.
Please note that if there are many blocking operations or cpu
sensitive computing we will need more nginx worker processes or jvm threads
under thread pool mode.
