### ISSUE TITLE
Example Clojure Project Is Not Working on Ubuntu 16.04

### ISSUE THREAD

**Issue by Grievoushead** [nginx-clojure/nginx-clojure#179]
I have followed all instructions from https://github.com/nginx-clojure/nginx-clojure/blob/master/example-projects/clojure-web-example/README.md

But when I run `sudo ./nginx` and then check error log
`cat logs/error.log ` the error shown and Nginx didn't started:

```
2017/07/19 09:08:49 [alert] 41358#0: worker process 41359 exited on signal 11 (core dumped)
2017/07/19 09:08:49 [error] 41366#0: jvm may be mad for wrong options! See hs_err_pid****.log for detail! restarted 2
2017/07/19 09:08:49 [alert] 41358#0: worker process 41366 exited with fatal code 2 and cannot be respawned
```

OS: Ubuntu 16.04.2 LTS
Java Version:
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
``` 

I noticed that if I remove everything clojure related from nginx.conf and try to restart the nginx is up and running.

**Comment by xfeep** [comment]
please show the result of 
```bash
cat /proc/version
```
Maybe it is same with issue #177 .

**Comment by Grievoushead** [comment]
@xfeep 
```
$ cat /proc/version
Linux version 4.4.0-81-generic (buildd@lgw01-02) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017

```

**Comment by Grievoushead** [comment]
@xfeep Yes, it's same issue as #177 and #175 and Kernel upgrade solve it.
I have upgraded to latest Kernel 4.12:
```
$ wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.12/linux-headers-4.12.0-041200_4.12.0-041200.201707022031_all.deb
$ wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.12/linux-headers-4.12.0-041200-generic_4.12.0-041200.201707022031_amd64.deb
$ wget http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.12/linux-image-4.12.0-041200-generic_4.12.0-041200.201707022031_amd64.deb
$ sudo dpkg -i *.deb
$ sudo reboot
```

Once re-login check Kernel version: `$ uname -sr`
It should be:
```
Linux 4.12.0-041200-generic
```

Source: https://www.tecmint.com/upgrade-kernel-in-ubuntu/

Probably this should be mentioned in readme section as common problems, since the Ubuntu image is taken from Azure and probably all who will used it face with same problem.

**Comment by xfeep** [comment]
@Grievoushead Thank you very much!  PRs welcome to make the example doc better!
