### ISSUE TITLE
memory leak with file handler

### ISSUE THREAD

**Issue by cernenwein** [nginx-clojure/nginx-clojure#180]
In ngx_http_clojure_module.c: the method ngx_http_clojure_expand_jvm_classpath

In this function the directory handle referenced by variable dir is never closed.
Each time nginx config is reloaded another directory handle is allocated, thus
there are at most MASTER_PROCESS_FD_LIIMIT - MASTER_OTHER_FDS reloads until the master will fail.

**Comment by cernenwein** [comment]
also 

static ngx_int_t ngx_http_clojure_module_init(ngx_cycle_t *cycle) {
--
(...)
ngx_http_clojure_shared_memory.size = cl * ssize;
ngx_http_clojure_shared_memory.name.len = sizeof("nginx_clojure_shared_zone");
ngx_http_clojure_shared_memory.name.data = (u_char *) "nginx_clojure_shared_zone";
ngx_http_clojure_shared_memory.log = cycle->log;
 
if (ngx_shm_alloc(&ngx_http_clojure_shared_memory) != NGX_OK) {
return NGX_ERROR;
}
(...)

 which is afaik called in master context each time configuration is reloaded.
The shared memory zone is not destroyed when the module is re-inited.

**Comment by xfeep** [comment]
@cernenwein Thank you!
This issue really hurts those cases where nginx reloads frequently.
Commit 460980d fixed it.
