### ISSUE TITLE
Unable to instrument

### ISSUE THREAD

**Issue by dennus** [nginx-clojure/nginx-clojure#186]
After creating wave-cfg and running nginx-clojure in corutine mode, I'm recieve this error message:

2017-08-09 08:40:54[error][31621][main]Unable to instrument:sun/net/www/http/HttpClient
nginx.clojure.wave.UnableToInstrumentException: Unable to instrument class sun/net/www/http/HttpClient.New(Ljava/net/URL;Ljava/net/Proxy;IZLsun/net/www/protocol/http/HttpURLConnection;)Lsun/net/www/http/HttpClient; because of synchronisation

Does it means, that I can't using this class in my application in coroutine mode?

**Comment by xfeep** [comment]
Did  `m` option is missed?  e.g.

```
jvm_options "-javaagent:jars/nginx-clojure-0.4.5.jar=mb";
```

`m` means allow nginx-clojure to clean synchronized effect.

**Comment by dennus** [comment]
No, option m is present

**Comment by xfeep** [comment]
Could you show a minimal example to reproduce it?

**Comment by xfeep** [comment]
Please make sure there's only one `-javaagent` jvm option.
