### ISSUE TITLE
Write partial content to buffer and send as stream

### ISSUE THREAD

**Issue by rachit20** [nginx-clojure/nginx-clojure#187]
I have a requirement where if client/browser requests for mp4 which will be huge in size , i can't go with whole file reading into memory as its causing OOM error .Also i dont want nginx default download . I am using nginx-clojure-0.4.4 where i need to open a channel to client and read mp4 specific byte ranges and keep writing to buffer and serve it and delete the file when last byte is served .Could you please help if this can be achieved . If yes then 
1. Does client need to send multiple request to nginx with byte ranges ?
2. Can server just return from header_filter only once and keep writing the bytes ?
3. Is there as way where a response ends from nginx , and i can have an event or listener kind of thing which will get invoked once response ends where i can delete the file ?

Also if possible please share some code snippets .

**Comment by xfeep** [comment]
There is an example https://github.com/nginx-clojure/nginx-clojure/blob/master/test/java/nginx/clojure/java/StreamingWriteHandler.java
