### ISSUE TITLE
Mysql issue

### ISSUE THREAD

**Issue by ibarrick** [nginx-clojure/nginx-clojure#190]
I'm having an issue trying to get nginx-clojure to work with Hikari-CP. The problem is that when the jar runs behind nginx-clojure I get AbstractMethodError on connection.isValid() which would seem to indicated that my MySQL driver is outdated and does not support JDBC4 API. However, I'm using the most recent MySQL driver and my code runs perfectly fine without nginx-clojure. I cannot seem to figure out why and how nginx-clojure is causing this issue for me.

**Comment by xfeep** [comment]
Please try the master branch.

**Comment by ibarrick** [comment]
That actually works! is there an easy way to use master from leiningen? I just built the jar and installed it locally to test but now I will have to publish it to clojars under a different group name unless there is a better way.

Thank you very much!
