### ISSUE TITLE
SharedMap support in nginx-clojure 0.4.4

### ISSUE THREAD

**Issue by rachit20** [nginx-clojure/nginx-clojure#192]
Hi,

I am using nginx-clojure 0.4.4 , nginx 1.11.0 . I am running multiple worker processes and want a static map which should be shared across workers . I came to know about SharedMap , but its not working as i expect . Basic functionalities like map.containsKey(), map.keySet() not working only . Please provide me the sample implementation of how to use put , get , containsKey etc .

NginxSharedHashMap<String,String> smap = NginxSharedHashMap.build("token_cache");
smap.put("hello", "guys");
**smap.containsKey("hello") // giving false**
smap.put("hello", "dude");

**Comment by xfeep** [comment]
Commit a1f9325 fix the bug about containsKey of nginx shared map.
keySet() was implemented since v0.4.5 but it should only be used for debug because it will fetch all keys in java heap every time.
