### ISSUE TITLE
NginxRequest.setVariable in a rewrite handler will hang when reload under threadpool mode

### ISSUE THREAD

**Issue by xfeep** [nginx-clojure/nginx-clojure#193]
Thanks to @alex-sherwin who show us a minimal example to reproduce this issue.see https://github.com/alex-sherwin/nginx-clojure-reload .

**Comment by xfeep** [comment]
Commit a8d201f fixed it.

**Comment by alex-sherwin** [comment]
Hi @xfeep 

This does seem to fix the scenario I showed (mostly, keep reading), thank you very much!  

The code no longer freezes up inside `NginxRequest.setVariable` and the requests complete with a proper HTTP response as expected.  I don't see the JVM hanging up inside any custom Java handlers at all now.

However, if you act like a real jerk and hammer it with reload signals, you can still get a request to hang indefinitely.  It's no longer inside a custom handler hook, though.

I've pushed my test with your changes to a branch `feature/fix` here: https://github.com/alex-sherwin/nginx-clojure-reload/tree/feature/fix

Doing the same process...

1. ./build.sh
2. ./run.sh
3. ./curl_loop.sh
4. ./reload.sh <-- repeat like crazy

You'll still end up with a hung request eventually

**Comment by xfeep** [comment]
Hi @alex-sherwin 

Thanks a lot for your so detail comment.

Please note that if reload repeats crazily , e.g. before jvm finish initialization reload comes again, nginx-clojure will take this as a mad state and will exit with error code to protect os from running out of resources. Typically a mad state is caused by some wrong configurations.

If you do not case about it you can change [the code](https://github.com/nginx-clojure/nginx-clojure/blob/v0.4.5/src/c/ngx_http_clojure_module.c#L1189) to 

```c
//max_temp_workers = 10 or greater. e.g. 100 
if ((ngx_int_t)ngx_atomic_fetch_add(ngx_http_clojure_jvm_be_mad_times, 1)
  >= ccf->worker_processes + max_temp_workers) {
```
