### ISSUE TITLE
Unable to read actual domain name from http request

### ISSUE THREAD

**Issue by rachit20** [nginx-clojure/nginx-clojure#194]
I am using nginx-clojure 0.4.4 and I need to read domain name from request url but unable to find a way 
to read it .

server {
	listen       80 default_server;
	listen 	443 http2 ssl default_server;
	server_name  *.demo;
......
}

The request url is https://xyz.demo/someurl
I need to read xyz.demo in nginx.clojure , is there any way to read it ? xyz.demo is pointing to IP where nginx is running .Please help .

**Comment by xfeep** [comment]
Java :


Map<String, String> headers = (Map<String, String>)
> request.get(Constants.HEADERS);
> String host = headers.get("Host");



Clojure

(（:headers request） "Host")
