### ISSUE TITLE
Worker Processes not freeing Memory, possible memory leak?

### ISSUE THREAD

**Issue by LethalMaus** [nginx-clojure/nginx-clojure#195]
Hi Xfeep,

I currently have a problem with Nginx-Clojure and am hoping you can help.
I am using Nginx-Clojure as a Java-ring-handler to communicate between our Frontend & Database.

Their are several Java methods which I call via a HTTP request to recieve data from an old DB, parse it & send send it to our new DB. This would be our heaviest process & once completed the Memory never gets freed from the Nginx Workers.
Basically after a few days Nginx will crash due to lack of memory.

I have checked over as much as possible over the last 2 months to find the problem. The Java code itself is unfortunately not the problem. Examples of the code can be given if necessary.

I am stumped and need help :(

If any details are missing I will get them for you:
Nginx Version: 1.8.0
Nginx-Clojure: 0.4.4
Centos 7 (Docker Container)

Nginx Config: See attachment'
[nginx.conf.txt](https://github.com/nginx-clojure/nginx-clojure/files/1477694/nginx.conf.txt)

**Comment by xfeep** [comment]
@LethalMaus 
It there any java crash log, e.g. hs_err_$pid.log, or error information in nginx error.log ?

**Comment by LethalMaus** [comment]
The only thing nginx eventually produces is an OOM error and the process stops. I can replicate the crash tomorrow and send you the logs from nginx.
I can find out about the java crash logs too.

I have developed a workaround inside the Java classes, which gracefully restarts the workers at the end of its process. So far this works, but its not a nice solution.
Once the Workers restart, the Memory is free to be used again.

Any ideas on how this could happen?

**Comment by xfeep** [comment]
Please add two java options 
1. `-XX:+HeapDumpOnOutOfMemoryError` 
1. `-XX:HeapDumpPath=/tmp/mydumpdirs`

 so that jvm will create a heap dump file in the dir `/tmp/mydumpdirs` when OOM happens. 
If we get the heap dump file we can use eclipse memory analyer or jhat to find what causes memory leak.

**Comment by LethalMaus** [comment]
Should I add this to the nginx config? or how should I pass the argument to JVM?

By the way I want to thank you for taking time out to help. I know you are pretty busy ;)

**Comment by xfeep** [comment]
Yes it should be added to the nginx config file.
But even without the dump heap configuration we can also use 
`jmap -dump:live,format=b,file=${my-heap-dump-file}  <pid>`
to dump heap before crash.

**Comment by LethalMaus** [comment]
I am unable to get the logs.
When it crashes the whole system crashes (on Docker).
The container is then down, in which case it didn't get a chance to log anything.
This is due to the setup that we have

I did watch it over the time, one worker increased from 90mb to 1,1gb in the space of an hour. Once the process stopped the Memory was never freed. This is surely some kind of memory leak isn't it?

Are their any other options?

**Comment by xfeep** [comment]
Why not use jmap to dump the heap before memory usage over 1GB, e.g. 500MB?
We can use eclipse memory analyer or jhat to analyze the dumped heap file to find what causes memory leak.

**Comment by LethalMaus** [comment]
Did a heap dump from a Nginx-Worker which had 1gb of memory consumption.
Unfortunately MAT doesn't say much for me (I'm not experienced enough to be able to depict the problem alone). I can have a workmate look at it but it will take some time (maybe Weeks).
I've uploaded the file in case you would like to have a look and see if you can find something, if you get the chance.
Thanks in advance
[nginx-heapdump.bin.txt](https://github.com/nginx-clojure/nginx-clojure/files/1487549/nginx-heapdump.bin.txt)

**Comment by xfeep** [comment]
@LethalMaus You dump file is too small and is only 8MB. Please try a larger one and compress it before uploading.
BTW github is not a good place to upload heap dump file so please try google driver.

**Comment by LethalMaus** [comment]
Ok, will make another one on Wednesday when I'm back in work.
Thanks very much for the tip. Will send the next one will Google Drive

**Comment by LethalMaus** [comment]
Every worker only delivers a small heap dump (8MB). The master process crashes and frees the memory when i try to dump its heap (which is always small anyway)
Did you have a look at the small heap dump file?
Any other possibilities?

**Comment by xfeep** [comment]
It seems there's nothing to do with nginx-clojure and we close it now. If somebody find any new information please reopen it or create another issue.
