### ISSUE TITLE
Cannot use custom NginxJavaHandlerFactory

### ISSUE THREAD

**Issue by mengzheng** [nginx-clojure/nginx-clojure#196]
The Ngnix Java Handler factory is dynamically loaded based on system property, "nginx.clojure.handler.factory.java". I want to create a custom NginxJavaHandlerFactory and pass it to Nginx Clojure via -Dnginx.clojure.handler.factory.java=<my custom factory classname>.

But Ngnix Clojure doesn't pick up the custom factory since the handler factory is hard coded in NginxClojureRT:
System.setProperty(NginxHandlerFactory.NGINX_CLOJURE_HANDLER_FACTORY_SYSTEM_PROPERTY_PREFIX + "java", "nginx.clojure.java.NginxJavaHandlerFactory");
		
Can we set this property to the built-in handler factory only if the property is not present?
if(System.getProperty(NginxHandlerFactory.NGINX_CLOJURE_HANDLER_FACTORY_SYSTEM_PROPERTY_PREFIX + "java") == null) {
	System.setProperty(NginxHandlerFactory.NGINX_CLOJURE_HANDLER_FACTORY_SYSTEM_PROPERTY_PREFIX + "java", "nginx.clojure.java.NginxJavaHandlerFactory");
}

**Comment by xfeep** [comment]
Please try 
```java
// in the jvm initialization handler
NginxHandlerFactory.register(String type,  NginxHandlerFactory factory)
```
to overwrite the built-in default handler factory.

**Comment by mengzheng** [comment]
Hi Yuexiang,

It doesn't work. The HANDLERS in NginxClojureRT are already populated
before the JVM Initialization Handler is executed. It is too late to
register handler factory at that point.

Thanks,
Jason

**Comment by mengzheng** [comment]
Hi xfeep,

It doesn't work. The HANDLERS in NginxClojureRT are already populated before the JVM Initialization Handler is executed. It is too late to register handler factory at that point.

**Comment by xfeep** [comment]
Please try to invoke NginxHandlerFactory.register(type,  factory) in the JVM Initialization Handler default constructor or  static initializer.

**Comment by mengzheng** [comment]
Yes, that works. Thanks a lot!

**Comment by mengzheng** [comment]
Hi Yuexiang,

Yes, that works. Thank you very much for your help!

Jason Zheng
Principal Engineer
Here.com
