### ISSUE TITLE
How to get response body size w/o reading the entire input buffer?

### ISSUE THREAD

**Issue by mengzheng** [nginx-clojure/nginx-clojure#197]
I can get the response body size in NginxJavaBodyFilter or StringFacedJavaBodyFilter, but it has to directly or indirectly read the entire input buffer. Note I only need the response body size (in bytes), not the body content. Is there an inexpensive way to get response body size?

**Comment by xfeep** [comment]
If the response has a Content-Length header we can use it directly.
Otherwise we can sum all values of bodyChunk.available() to get it.
