### ISSUE TITLE
how did nginx-clojure's exception happens !

### ISSUE THREAD

**Issue by OneHappyStone** [nginx-clojure/nginx-clojure#198]
2017-11-16 19:53:01[info][12481][main]nginx-clojure run on thread pool mode,  coroutineEnabled=false
Exception in thread "main" java.lang.NullPointerException
	at nginx.clojure.NginxClojureRT.handlePostedResponse(NginxClojureRT.java:1400)
	at nginx.clojure.NginxClojureRT.handlePostEvent(NginxClojureRT.java:1222)
	at nginx.clojure.NginxClojureRT.handlePostEvent(NginxClojureRT.java:1353)
2017/11/16 19:53:01 [error] 12481#0: ngx clojure: ngx_http_clojure_handle_post_event failed,rp=27792336u, rc=-1
2017-11-16 19:53:01[error][12481][main]handle post poll task event error
java.lang.NullPointerException
	at nginx.clojure.NginxClojureRT.handlePostEvent(NginxClojureRT.java:1317)
	at nginx.clojure.NginxClojureRT.handlePostEvent(NginxClojureRT.java:1353)
2017/11/16 19:53:01 [error] 12481#0: ngx clojure: ngx_http_clojure_handle_post_event failed,rp=2233785419324168744u, rc=500
2017/11/16 19:53:29 [error] 3347#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:self signed certificate in certificate chain) while requesting certificate status, responder: ocsp.godaddy.com, peer: 182.50.136.239:80, certificate: "/etc/ssl/certs/STAR_shishike_com_bundle.crt"
2017/11/16 19:53:30 [error] 12246#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:self signed certificate in certificate chain) while requesting certificate status, responder: ocsp.godaddy.com, peer: 182.50.136.239:80, certificate: "/etc/ssl/certs/STAR_shishike_com_bundle.crt"
2017/11/16 19:55:27 [crit] 12246#0: *7210620 SSL_do_handshake() failed (SSL: error:1417D18C:SSL routines:tls_process_client_hello:version too low) while SSL handshaking, client: 184.105.247.194, server: 0.0.0.0:443
2017/11/16 19:55:51 [error] 12481#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:self signed certificate in certificate chain) while requesting certificate status, responder: ocsp.godaddy.com, peer: 182.50.136.239:80, certificate: "/etc/ssl/certs/STAR_shishike_com_bundle.crt"
2017/11/16 19:55:54 [error] 7080#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:self signed certificate in certificate chain) while requesting certificate status, responder: ocsp.godaddy.com, peer: 182.50.136.239:80, certificate: "/etc/ssl/certs/STAR_shishike_com_bundle.crt"
2017/11/16 19:57:05 [crit] 12246#0: *7212263 SSL_do_handshake() failed (SSL: error:1417D18C:SSL routines:tls_process_client_hello:version too low) while SSL handshaking, client: 216.218.206.69, server: 0.0.0.0:443
2017/11/16 20:02:12 [error] 12481#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:self signed certificate in certificate chain) while requesting certificate status, responder: ocsp.godaddy.com, peer: 182.50.136.239:80, certificate: "/etc/ssl/certs/STAR_shishike_com_bundle.crt"
2017/11/16 20:08:50 [error] 11283#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:self signed certificate in certificate chain) while requesting certificate status, responder: ocsp.godaddy.com, peer: 182.50.136.239:80, certificate: "/etc/ssl/certs/STAR_shishike_com_bundle.crt"
2017/11/16 20:10:28 [error] 3347#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:self signed certificate in certificate chain) while requesting certificate status, responder: ocsp.godaddy.com, peer: 182.50.136.239:80, certificate: "/etc/ssl/certs/STAR_shishike_com_bundle.crt"
2017/11/16 20:10:30 [error] 12246#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:self signed certificate in certificate chain) while requesting certificate status, responder: ocsp.godaddy.com, peer: 182.50.136.239:80, certificate: "/etc/ssl/certs/STAR_shishike_com_bundle.crt"
2017/11/16 20:12:21 [alert] 16890#0: worker process 11283 exited on signal 6
2017-11-16 20:12:21[info][13625][main]nginx-clojure run on thread pool mode,  coroutineEnabled=false
2017/11/16 20:12:31 [error] 12481#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:self signed certificate in certificate chain) while requesting certificate status, responder: ocsp.godaddy.com, peer: 182.50.136.239:80, certificate: "/etc/ssl/certs/STAR_shishike_com_bundle.crt"
2017/11/16 20:15:01 [alert] 16890#0: worker process 12246 exited on signal 6
2017-11-16 20:15:01[info][13929][main]nginx-clojure run on thread pool mode,  coroutineEnabled=false
2017/11/16 20:18:37 [error] 13625#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:self signed certificate in certificate chain) while requesting certificate status, responder: ocsp.godaddy.com, peer: 182.50.136.239:80, certificate: "/etc/ssl/certs/STAR_shishike_com_bundle.crt"
2017/11/16 20:20:40 [error] 20431#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:self signed certificate in certificate chain) while requesting certificate status, responder: ocsp.godaddy.com, peer: 182.50.136.239:80, certificate: "/etc/ssl/certs/STAR_shishike_com_bundle.crt"
2017/11/16 20:23:21 [error] 13929#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:self signed certificate in certificate chain) while requesting certificate status, responder: ocsp.godaddy.com, peer: 182.50.136.239:80, certificate: "/etc/ssl/certs/STAR_shishike_com_bundle.crt"
2017/11/16 20:26:50 [error] 3347#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:self signed certificate in certificate chain) while requesting certificate status, responder: ocsp.godaddy.com, peer: 182.50.136.239:80, certificate: "/etc/ssl/certs/STAR_shishike_com_bundle.crt"
2017/11/16 20:26:51 [error] 12481#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:self signed certificate in certificate chain) while requesting certificate status, responder: ocsp.godaddy.com, peer: 182.50.136.239:80, certificate: "/etc/ssl/certs/STAR_shishike_com_bundle.crt"
2017/11/16 20:27:47 [error] 13625#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:self signed certificate in certificate chain) while requesting certificate status, responder: ocsp.godaddy.com, peer: 182.50.136.239:80, certificate: "/etc/ssl/certs/STAR_shishike_com_bundle.crt"
2017/11/16 20:31:32 [alert] 16890#0: worker process 12481 exited on signal 6
2017-11-16 20:31:33[info][15065][main]nginx-clojure run on thread pool mode,  coroutineEnabled=false
2017/11/16 20:35:45 [alert] 7080#0: *7243254 writev() failed (14: Bad address) while sending to client, client: 114.55.124.186, server: citest*.shishike.com, request: "GET /auth/tal/syncApi/getDataPermission?shopID=850017165&brandID=2479&includeLogicDeleted=true&maxUpdateTime=1498166653000&maxId=7958&limit=40&kry-api-brand-id=2479 HTTP/1.1", upstream: "http://171.16.30.21:80/auth/tal/syncApi/getDataPermission?shopID=850017165&brandID=2479&includeLogicDeleted=true&maxUpdateTime=1498166653000&maxId=7958&limit=40", host: "citestb.shishike.com"
2017/11/16 20:39:00 [alert] 16890#0: worker process 13929 exited on signal 6
2017-11-16 20:39:00[info][15517][main]nginx-clojure run on thread pool mode,  coroutineEnabled=false
Exception in thread "main" java.lang.NullPointerException
	at nginx.clojure.NginxClojureRT.handlePostedResponse(NginxClojureRT.java:1400)
	at nginx.clojure.NginxClojureRT.handlePostEvent(NginxClojureRT.java:1222)
	at nginx.clojure.NginxClojureRT.handlePostEvent(NginxClojureRT.java:1353)
2017/11/16 20:39:00 [error] 15517#0: ngx clojure: ngx_http_clojure_handle_post_event failed,rp=27627344u, rc=-1
2017/11/16 20:39:21 [crit] 7910#0: *7249573 SSL_do_handshake() failed (SSL: error:1417D18C:SSL routines:tls_process_client_hello:version too low) while SSL handshaking, client: 218.89.222.142, server: 0.0.0.0:443
2017/11/16 21:03:02 [alert] 16890#0: worker process 7910 exited on signal 6
2017-11-16 21:03:02[info][17902][main]nginx-clojure run on thread pool mode,  coroutineEnabled=false
2017/11/16 21:11:24 [error] 15517#0: OCSP_basic_verify() failed (SSL: error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:Verify error:self signed certificate in certificate chain) while requesting certificate status, responder: ocsp.godaddy.com, peer: 182.50.136.239:80, certificate: "/etc/ssl/certs/STAR_shishike_com_bundle.crt"
2017/11/16 21:15:40 [alert] 16890#0: worker process 13625 exited on signal 6

**Comment by xfeep** [comment]
Which version do you use?

**Comment by OneHappyStone** [comment]
my version is 0.4.5.
        <dependency>
            <groupId>nginx-clojure</groupId>
            <artifactId>nginx-clojure</artifactId>
            <version>0.4.5</version>
        </dependency>

**Comment by xfeep** [comment]
It seems  there 's a bad damaged memory issue.
Are there any other nginx modules? Could you please show an minimal case to reproduce it?

**Comment by OneHappyStone** [comment]
After repeated pressure measurement，The problem was happended when I use header filter and rewriteHandler together. (The QPS is 70+)
```xml
location / {
          header_filter_type 'java';
          header_filter_name 'com.handler.RemoveAndAddMoreHeaders';
          location / {
                always_read_body on;
                rewrite_handler_type 'java';
                rewrite_handler_name  'com.handler.AbstractNginxJavaRingHandler';
                proxy_pass http://current_zone;
            }
  }
```
when I found 
`
8. Bug Fix: NullPointerExecption will happen when multiple rewrite handlers are invoked for one request
`
in release notes of nginx-clojure 0.4.5。

so I removed header filter 
and repeated pressure measurement again(no matter the QPS is 70+ or 300+), the problem of NullPointException disappeared。

**Comment by xfeep** [comment]
@OneHappyStone 
Thanks for your so detail description!
Header filter really has a bug when nginx-clojure runs with thread pool mode.
There are two work around methods

1. Use default mode instread of thread pool mode
2. OR use a safe way to udpate headers map with thread pool mode, e.g.

```java

public Object[] doFilter(int status, Map<String, Object> request, 
                                     Map<String, Object> responseHeaders)
			throws IOException {
		/**
		 * 1. compute some values here
		 */
		//// compute code here
		
		/**
		 * 2. modify responseHeaders in the safe way
		 */
		NginxClojureRT.postPollTaskEvent(()->{
			responseHeaders.remove("Content-Length");
			responseHeaders.put("MyHost", "MyTestServer");
		});
		return Constants.PHASE_DONE;
	}

```

**Comment by xfeep** [comment]
Since v0.5.1, nginx-clojure uses delayed header update to make header filter more safe with thread-pool mode.
