### ISSUE TITLE
Nginx hangs forever when creating sub-request in nginx-clojure-0.4.4

### ISSUE THREAD

**Issue by rachit20** [nginx-clojure/nginx-clojure#199]
I am having a scenario where i am sending a request to nginx with worker_process 1 using nginx-clojure java module in 'content-handler' type interceptor , inside that i am performing extraction of thumbnail by giving m3u8 url to ffmpeg source which internally calls one more request url (key url) to same nginx running on same port after which is it never returns . 

               Process process = null;
		ProcessBuilder pb = new ProcessBuilder(s); // s is command array
		pb.redirectOutput(Redirect.INHERIT);
		pb.redirectError(Redirect.INHERIT);
		process = pb.start();
		log.info("Response error from ffmpeg:" + process.getErrorStream());
		int exitVal = process.waitFor();
		log.info("exit val:" + exitVal);

So first thread will be waiting at  process.waitFor(); forever and never return back . After which all request coming to nginx server will be waiting forever which is very dangerous situation  . Can you please help with this ? I need to understand the problem here and solution for the same . I believe nginx should handle multiple requests but here something strange happening .

**Comment by xfeep** [comment]
By default nginx worker only use single thread to handle requests. 
Please try thread pool mode but note that if ffmpeg is too slow nginx will be blocked eventually when many requests are incoming.
