### ISSUE TITLE
Add or remove a location directive from clojure

### ISSUE THREAD

**Issue by derekchiang** [nginx-clojure/nginx-clojure#200]
Is it possible to dynamically add/remove a location directive using `nginx-clojure`?  That is, my Clojure code might at some point during run time decide to add or remove a location directive for proxying purposes.

**Comment by xfeep** [comment]
We can not use nginx-clojure to dynamically add/remove locations.
Please try to use [rewrite handler](http://nginx-clojure.github.io/configuration.html#25-nginx-rewrite-handler) with which we can change the proxying behavior.

**Comment by derekchiang** [comment]
@xfeep thanks for the quick response.  I don't see how I could use rewrite handler to add or remove a new proxy location though.  Could you give an example?

**Comment by xfeep** [comment]
@derekchiang 
Is your case  about static content locations or proxy locations?
If it is about static content locations a content handler can be used to service static content dynamically.
If it is about proxy locations a rewrite handler can be used to proxy to dynamical target server.

**Comment by derekchiang** [comment]
@xfeep I understand that you can use a rewrite handler to proxy to a *different* location.

However, I'm wondering if you could *add* or *remove* a proxy location dynamically.  Like, let's say initially I'm only proxying the path `/foo` to `http://www.foo.com`.  Is it possible, while the server is running, to dynamically *add* another proxy path `/bar` which points to `http://www.bar.com`?

**Comment by xfeep** [comment]
A static root location with a rewrite handler? e.g.

```nginx
set target "";
location / {
   rewrite_handler_type java;
   rewrite_handler_name com.my.MyRewriteHandler;
   proxy_pass $target;
}
```

```java
// in MyRewriteHandler
NginxJavaRequest r = (NginxJavaRequest)requset;
String uri = r.uri();

//It is a very simple case.
//But we can dynamically set variable by more complex logic.
if (uri.startsWith("/foo")) {
   request.setVariable("target", "http://www.foo.com/");
} else if (uri.statsWith("/bar")) {
  request.setVariable("target", "http://www.bar.com/");
}
```
