### ISSUE TITLE
[Question] Possible to modify headers before Proxypass?

### ISSUE THREAD

**Issue by prasann** [nginx-clojure/nginx-clojure#202]
Great job with this library !!

We have a clojure based access handler, that does some processing before proxying it to the downstream services. 
Processing of request involves, adding and removing some headers.

Currently, we use `set-ngx-var!` and then later refer that variable in the `proxy_set_header` 
in nginx.conf. Works great !!

Wanted to know whether the same thing can be done elegantly in clojure? 

Especially we would like to delete few headers that match a pattern. 

Something in the lines of `proxy_set_header starts-with-* ''` will be fantastic. 

I know that nginx.conf by default doesn't support wildcard in `proxy_set_header`

**Comment by xfeep** [comment]
Sorry we can't do the same thing elegantly in clojure.
Maybe this function can be in the future release.

**Comment by prasann** [comment]
Sure. Thanks for the response. I'm closing this question.
