### ISSUE TITLE
Unable to run nginx with nginx-clojure-0.4.5 module

### ISSUE THREAD

**Issue by mchalep** [nginx-clojure/nginx-clojure#204]
nginx newbie here.
I am getting the following errors when starting nginx with the nginx-clojure-0.4.5 module compiled.

Exception in thread "main" java.lang.RuntimeException: can not load factory:nginx.clojure.clj.NginxClojureHandlerFactory
Caused by: java.lang.NoClassDefFoundError: clojure/lang/RT
Caused by: java.lang.ClassNotFoundException: clojure.lang.RT

I have put the nginx-closure-0.4.5.jar file only in /opt/mylibs  (What else goes into this location??).
I am running CentOS 7 with nginx started via systemd.

The two JVM settings are:
jvm_path "/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/amd64/server/libjvm.so";
jvm_classpath /opt/mylibs/*;                              (contains nginx-clojure-0.4.5.jar only)

The system hangs when I start nginx and will not work until I remove the above two lines in /etc/nginx/nginx.conf.

I have been trying to find some information regarding this but I haven't found anything useful yet. 

Would be very grateful if someone could please advise.

Patrick McHale

**Comment by mchalep** [comment]
Hmm, If I comment out the line with "content_handler_code" - nginx does not hang.

	location /clojure {
       		content_handler_type 'clojure';
       		#content_handler_code ' 
OR
    	location /groovy {
		handler_type 'groovy';
    		#handler_code '
but without this line - no desired functionality would occur.

Patrick

**Comment by xfeep** [comment]
If you use clojure handler clojure runtime jar is needed in your classpath.
If you use groovy handler groovy runtime jar is needed in your classpath.

**Comment by mchalep** [comment]
I have both and still cannot get the module to work. I put in in
nginx-clojure-0.45.jar and also clojure-0.5.1.jar and still no joy.



Patrick



*From:* Zhang,Yuexiang [mailto:notifications@github.com]
*Sent:* Friday, 22 December 2017 3:27 AM
*To:* nginx-clojure/nginx-clojure <nginx-clojure@noreply.github.com>
*Cc:* Patrick McHale <patrick.mchale@nzx.com>; Author <
author@noreply.github.com>
*Subject:* Re: [nginx-clojure/nginx-clojure] Unable to run nginx with
nginx-clojure-0.4.5 module (#204)



If you use clojure handler clojure runtime jar is needed in your classpath.
If you use groovy handler groovy runtime jar is needed in your classpath.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nginx-clojure/nginx-clojure/issues/204#issuecomment-353363903>,
or mute the thread

**Comment by mchalep** [comment]
Success – I again added the clojure-0.5.1.jar runtime and this time it has
worked. Not sure why it didn’t before when I added this.



Where do I get the groovy handler runtime.jar from?



Regards



Patrick



*From:* Zhang,Yuexiang [mailto:notifications@github.com]
*Sent:* Friday, 22 December 2017 3:27 AM
*To:* nginx-clojure/nginx-clojure <nginx-clojure@noreply.github.com>
*Cc:* Patrick McHale <patrick.mchale@nzx.com>; Author <
author@noreply.github.com>
*Subject:* Re: [nginx-clojure/nginx-clojure] Unable to run nginx with
nginx-clojure-0.4.5 module (#204)



If you use clojure handler clojure runtime jar is needed in your classpath.
If you use groovy handler groovy runtime jar is needed in your classpath.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nginx-clojure/nginx-clojure/issues/204#issuecomment-353363903>,
or mute the thread

**Comment by mchalep** [comment]
Located groovy runtime.jar. All of the desired functionality is now working for me, and I can close this.
