### ISSUE TITLE
Cannot run Groovy (external) example routine. Inline code runs fine

### ISSUE THREAD

**Issue by mchalep** [nginx-clojure/nginx-clojure#205]
Hi, 

I am having a problem with running the external "groovy" example routine. Using the inline option it works fine. I have checked permissions, and the code itself which is straight out of the Nginx 3rd Party modules example list. When trying to run this via an external routine it fails. I have checked paths and copied the external code into a mytest subdirectory as from another issue logged.
        
        This section fails
        location /groovy {
                handler_type 'groovy';
                handler_name 'mytest.HelloGroovy';
        }

        This section "Works" when un-commented:
        #location /groovy {
        #       handler_type 'groovy';
        #       handler_code '
        #       import nginx.clojure.java.NginxJavaRingHandler;
        #       import java.util.Map;
        #               public class HelloGroovy implements NginxJavaRingHandler {
        #                       public Object[] invoke(Map<String, Object> request){
        #                               return [200, //http status 200
        #                                       ["Content-Type":"text/html"], //headers map
        #                                       "Hello, Groovy & NGINX!"]; //response body can be string, File or Array/Collection of them
        #                       }
        #               }
        #       ';
        #}

which produces
2017/12/22 11:11:21 [error] 23789#23789: invalid groovy content_handler code : mytest.HelloGroovy
2017/12/22 11:11:22 [alert] 23787#23787: worker process 23789 exited with fatal code 2 and cannot be respawned

Would be grateful if someone could advise.

Patrick

**Comment by xfeep** [comment]
The groovy file of HelloGroovy.groovy or the compiled class should be in the classpath of jvm.

**Comment by mchalep** [comment]
Yes, the HelloGroovy.groovy file is located in the classpath location. I have the same issue with the external java routine as well. 

I have three jar files in the classpath  
clojure-1.8.0.jar
nginx-closure-0.4.5.jar
groovy-2.3.4.jar

Is there any other jar files that should be in my classpath for this to work. I really wish I could get these two "external" java or groovy locations to run properly. Everytime I have the content_handler_name uncommented - the nginx web server hangs and no web pages appear.

location /groovy {
               content_handler_type 'groovy';
        #     content_handler_name 'mytest.HelloGroovy';
        }
location /java {
                content_handler_type 'java';
        #      content_handler_name 'mytest.HelloService';
        }

Would be extremely grateful for some help with this.

Patrick

**Comment by xfeep** [comment]
Please show your whole nginx.conf.

**Comment by mchalep** [comment]
The whole nginx.conf file is here. The routines I wish to run are in separate files (at the end).

user  nginx;
worker_processes auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    #gzip  on;
    # reserve 1MB under the name 'proxied' to track uploads
    vhost_traffic_status_zone;
    upload_progress proxied 1000m;

    jvm_path "/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/amd64/server/libjvm.so";
    jvm_classpath "/opt/mylibs/*";

    jvm_options "-Xms256m";
    jvm_options "-Xmx256m";

    server {
        listen       127.0.0.1 default;
        server_name  localhost;

        root /usr/share/nginx/html;

        location / {
            # proxy to upstream server
            proxy_pass http://127.0.0.1;
            proxy_redirect default;

        }
        location ^~ /progress {
            # report uploads tracked in the 'proxied' zone
            report_uploads proxied;
        }
    }
    include /etc/nginx/conf.d/*.conf;
}

**Comment by mchalep** [comment]
The error log entries I get is:

Exception in thread "main" java.lang.RuntimeException: can not create nginx handler for name : mytest.HelloService
        at nginx.clojure.java.NginxJavaHandlerFactory.newInstance(NginxJavaHandlerFactory.java:33)
        at nginx.clojure.NginxHandlerFactory.fetchHandler(NginxHandlerFactory.java:46)
        at nginx.clojure.NginxClojureRT.registerCode(NginxClojureRT.java:866)
Caused by: java.lang.ClassNotFoundException: mytest.HelloService
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at nginx.clojure.java.NginxJavaHandlerFactory.newInstance(NginxJavaHandlerFactory.java:23)
        ... 2 more
2018/01/03 10:58:31 [error] 1520#1520: invalid java content_handler code : mytest.HelloService
2018/01/03 10:58:33 [alert] 1519#1519: worker process 1520 exited with fatal code 2 and cannot be respawned

**Comment by xfeep** [comment]
`ClassNotFoundException` means the classpath is wrong.The folder /opt/mylibs should has below structure.

```
/opt/mylibs
                /mytest
                            /HelloService.class
                            /HelloGroovy.class or HelloGroovy.groovy
               /nginx-clojure-0.4.5.jar
               /groovy-2.3.4.jar  -- only if you use groovy handler
               /clojure-1.8.0.jar -- only if you use clojure handler.
```

**Comment by mchalep** [comment]
Hi xfeep,

Thanks for that. Have made sure the file structure is set out as you mentioned. Still have the same problem though. When I restart the nginx service it still says "waiting for 10.3.4.105' (nginx server hangs). 

If I comment out the offending line in "/java" or "/groovy", all of the other routines start to work. I just don't know where I am going wrong here as I have created all of the other routines successfully. 

Patrick

**Comment by mchalep** [comment]
Have managed to get this working but via a very unconventional and non sensible means:
1. Changed  
location /java {
           content_handler_type 'java';
           content_handler_name 'Hello';      #was mytest.Hello - I removed mytest.
        }
2. Changed Hello.java  (removed package mytest in line)
/* package mytest; */

3. Recompiled the above and placed this in the "mytest" subdirectory in the classpath location.
javac -cp "/opt/mylibs/*" Hello.java

Have rebooted machine and still works. The reference to mytest in the coding has been completely 
removed but the location of the file still needs to be in a "mytest" subdirectory below the 
classpath definition, in order to work. This is rather crazy as it shouldn't work - but it does. 

Patrick

**Comment by xfeep** [comment]
@mchalep 
Sorry. The folder structure should be like 

```
/opt/mylibs
               /classes 
                           /mytest
                                     /HelloService.class
                                     /HelloGroovy.class or HelloGroovy.groovy
               /nginx-clojure-0.4.5.jar
               /groovy-2.3.4.jar  -- only if you use groovy handler
               /clojure-1.8.0.jar -- only if you use clojure handler.
```
The jvm_classpath directive doc can be found at http://nginx-clojure.github.io/directives.html#jvm_classpath

**Comment by mchalep** [comment]
That's it - now working correctly without the changes above I needed to do. Thank you. Haven't quite got the Groovy example working yet. I have compiled it with the following:
groovyc -cp :/opt/mylibs/* HelloGroovy.groovy but when I go to look at the webpage it is still giving me a 404 page not found error. The nginx webserver is still running which is a good sign. Just need to diagnose why this is not working for me.

**Comment by xfeep** [comment]
We  has a test case in integration tests.

e.g. In nginx-plain.conf
```
       location /groovy2 {
          content_handler_type 'groovy';
          content_handler_name 'nginx.clojure.groovy.HelloGroovy2';
       }
```

So we closed it now.
