### ISSUE TITLE
nginx clojure dynamic module compile steps

### ISSUE THREAD

**Issue by vanibandi** [nginx-clojure/nginx-clojure#206]
Under releases, its mentioned that version 0.4.5 has New Feature: Support to be compiled as Nginx dynamic modul. Can you please provide steps for the same. I tried these https://www.nginx.com/blog/compiling-dynamic-modules-nginx-plus/ but not able to find corresponding conf file.

**Comment by vanibandi** [comment]
also please share the configuration steps like after loading module, do I need to still include jars?

**Comment by xfeep** [comment]
```
#If nginx source is checked out from hg, please replace ./configure with auto/configure
$./configure \
    --add-dynamic-module=nginx-clojure/src/c
$ make modules
```

If you enable nginx-clojure dynamic module you still need configure jvm related settings such as jvm_path, jvm_classpath ,etc.

**Comment by xfeep** [comment]
More details about configuration can be found from http://nginx-clojure.github.io/configuration.html#21-jvm-path--class-path--other-jvm-options

**Comment by vanibandi** [comment]
Tks a ton. This worked
