### ISSUE TITLE
request_id for logging

### ISSUE THREAD

**Issue by vanibandi** [nginx-clojure/nginx-clojure#207]
we want to corelate nginx logs and clojure rewrite handler logs. nginx provide $request_id as transaction id. i was able to use add header directive to add it as a custom header but i am unable to read it in the rewrite handler. can u guide how we can do so.

**Comment by xfeep** [comment]
Please try 


```clojure
;;; Clojure
 (get-ngx-var req "request_id")
```

```java
// java
NginxJavaRequest r = (NginxJavaRequest) request;
r.getVariable("request_id")
```
