### ISSUE TITLE
Can I use log4j ThreadContext inside NginxJavaRingHandler?

### ISSUE THREAD

**Issue by mengzheng** [nginx-clojure/nginx-clojure#211]
I want to use log4j ThreadContext to add an unique id in the application log. 

Is the code below working for logging an unique id in log4j?

import org.apache.logging.log4j.ThreadContext;
class MyRequestHandler implements NginxJavaRingHandler {
   static Logger log = ...;

  public Object[] invoke(Map<String, Object>  request) {
      String traceId = UUID.randomUUID().toString();
      ThreadContext.push(traceId); // Add the fishtag, so it shows up in log4j log

      log.debug("Message 1");
      // do some operations here 
      log.debug("Message 2");
   
     ThreadContext.pop();
     return Constants.PHASE_DONE;
}

Once the invoke method is called, I assume the worker thread will not handle other requests until it exits the invoke method. Is my assumption correct?

Thanks!

**Comment by xfeep** [comment]
> Once the invoke method is called, I assume the worker thread will not handle other requests until it exits the invoke method. Is my assumption correct?

The answer is YES if you use default mode or thread pool mode.
