### ISSUE TITLE
Run Java web application using Nginx without tomcat

### ISSUE THREAD

**Issue by bhaumikbarad** [nginx-clojure/nginx-clojure#212]
Hi,

I am having Java web application (with RESTful webservices). Currently it is running on tomcat server.
Is is possible to run Java web application using Nginx server only without tomcat server ??

Please suggest if you have any idea.

Thanks,
Bhaumik

**Comment by xfeep** [comment]
If you use RESTful webservices without servlet or server side script such as JSP please try [nginx-jersey](https://github.com/nginx-clojure/nginx-clojure/tree/master/nginx-jersey) which is based on nginx-clojure.
