### ISSUE TITLE
Support  java/clojure log handlers 

### ISSUE THREAD

**Issue by mengzheng** [nginx-clojure/nginx-clojure#213]
In my project, I need to pipe access log information to backend for accounting purpose. The nginx-clojure supports header filter and body filter now, but they are not suitable for this purpose. It would be nice that it supports log handler which is called right before nginx writes log entry to the access log. 

Does nginx-clojure support the log handler now? If not, do we have plan to support it in near future? 

To make it easier, I can add the log handler via Java code directly w/o configuration changes. I don't need to modify the log values. How difficult to add such a handler?

Thanks!

**Comment by xfeep** [comment]
0.5.0 will support log handler and it will be released this weekend.

**Comment by xfeep** [comment]
0.5.0 has been released!
