### ISSUE TITLE
No way to get $request_uri from nginx in the NginxJavaRingHandler.invoke(..) request map

### ISSUE THREAD

**Issue by kenmccracken** [nginx-clojure/nginx-clojure#215]
I am using nginx with nginx-clojure to talk to custom Java code.  I have my own implementation of NginxJavaRingHandler in which I want to route the HTTP request path to a set of routes defined in my server.  However, it seems that when my NginxJavaRingHandler is invoked by the nginx-clojure module, the original request_uri is not available.  Instead, only the URL-decoded value for "uri" is available in the Map<String, Object> request.  I looked through the source code and couldn't find an easy way to configure the request_uri on, or to extend the set of values that are considered for that request property map.  Is there a way to configure NginxJavaRingHandler to see the original request path?  If not, what is the recommended approach for adding such a feature?

MyNginxJavaRingHandler invoke method snippets:

`
   public Object[] invoke(Map<String, Object>  request) {
        printRequest(request);

        Object [] returns = null;
        // ...
        return returns;
    }

    private void printRequest(Map<String, Object> request) {
        if (log.isDebugEnabled()) {
            if (!request.isEmpty()) {
                for (Map.Entry<String, Object> requestEntry : request.entrySet()) {
                    log.debug("Key is {}; Object is {}", requestEntry.getKey(), requestEntry.getValue());
                }
            } else {
                log.debug("Request map is empty");
            }
        }
    }
  `

When I issue a GET request for "/v1/projects/foo%3Awidget%2FPROJ-6506f454-cb37-4778-9178-328831e1d321", I get the following output in my logs:

> 2018-09-05 13:38:16,594 [nginx-clojure-worker-14] DEBUG [NginxRequestHandler (:)] | Key is uri; Object is /v1/projects/foo:widget/PROJ-6506f454-cb37-4778-9178-328831e1d321
2018-09-05 13:38:16,594 [nginx-clojure-worker-14] DEBUG [NginxRequestHandler (:)] | Key is body; Object is null
2018-09-05 13:38:16,594 [nginx-clojure-worker-14] DEBUG [NginxRequestHandler (:)] | Key is headers; Object is {Authorization=Bearer redacted, Host=redacted, Connection=Keep-Alive, User-Agent=Apache-HttpClient/4.5.2 (Java/1.8.0_162), Accept-Encoding=gzip,deflate}
2018-09-05 13:38:16,594 [nginx-clojure-worker-14] DEBUG [NginxRequestHandler (:)] | Key is server-port; Object is 8443
2018-09-05 13:38:16,594 [nginx-clojure-worker-14] DEBUG [NginxRequestHandler (:)] | Key is server-name; Object is localhost
2018-09-05 13:38:16,594 [nginx-clojure-worker-14] DEBUG [NginxRequestHandler (:)] | Key is remote-addr; Object is redacted
2018-09-05 13:38:16,594 [nginx-clojure-worker-14] DEBUG [NginxRequestHandler (:)] | Key is query-string; Object is null
2018-09-05 13:38:16,594 [nginx-clojure-worker-14] DEBUG [NginxRequestHandler (:)] | Key is scheme; Object is https
2018-09-05 13:38:16,594 [nginx-clojure-worker-14] DEBUG [NginxRequestHandler (:)] | Key is request-method; Object is get
2018-09-05 13:38:16,594 [nginx-clojure-worker-14] DEBUG [NginxRequestHandler (:)] | Key is content-type; Object is null
2018-09-05 13:38:16,594 [nginx-clojure-worker-14] DEBUG [NginxRequestHandler (:)] | Key is character-encoding; Object is null

While my nginx-access.log contains the following line 

> [05/Sep/2018:13:38:16 +0000] url="/v1/projects/foo%3Awidget%2FPROJ-6506f454-cb37-4778-9178-328831e1d321" method="GET" ...

My nginx log_format.conf includes

> ... url="$request_uri" method="$request_method" ...

On the surface it seems that nginx-clojure's NginxJavaRingHandler makes only the URL-decoded path available, while the nginx logs appear to have a "request_uri" variable that preserves the path, though I may be missing something.

Without such a capability to access the HTTP Request path in my Java code, you can imagine it would get more difficult to deal with longer paths such as children of the project, as the REST path translation for swagger path "/v1/projects/{project}/children/{child}".

**Comment by dennus** [comment]
You can directly get request_uri variable, using NginxClojureRT.getNGXVariable method

**Comment by xfeep** [comment]
```java
// java
NginxJavaRequest r = (NginxJavaRequest) request;
r.getVariable("request_uri")
```

```clojure
;;; Clojure
 (get-ngx-var req "request_uri")
```

**Comment by kenmccracken** [comment]
Thank you for the responses.  I think that @dennus and @xfeep 's responses are related, as in the code I see 

`
	public String getVariable(String name) {
		return NginxClojureRT.getNGXVariable(r, name);
	}
`

As suggested, I've invoked the wrapper getVariable("request_uri") method on invoke()'s request variable.  It seems to work correctly from a functional perspective, and gets me the original path / request_uri.

My only concern is that I'm using runtime-casting.  My actual code looks like

`
    private void printRequest(Map<String, Object> request) {
        if (log.isDebugEnabled()) {
            if (!request.isEmpty()) {
                for (Entry<String, Object> requestEntry : request.entrySet()) {
                    log.debug("Key is {}; Object is {}", requestEntry.getKey(), requestEntry.getValue());
                }

                // java
                if (request instanceof  NginxJavaRequest) {
                    NginxJavaRequest nginxJavaRequest = (NginxJavaRequest) request;
                    String request_uri = nginxJavaRequest.getVariable("request_uri");
                    log.debug("nginxJavaRequest request_uri={}", request_uri);
                }
            } else {
                log.debug("Request map is empty");
            }
        }
    }
`

Because I am using runtime-casting, when I look at the interface definition, the object's type for the "request" variable in  

`
    public Object[] invoke(Map<String, Object>  request) {
`

method could change from release to release, without warning.  You could also argue I am breaking some intended abstraction barrier.

Should I be concerned about this going forward?  Could the invoke method interface be modified to specify a type that exposes the method getVariable() without the need for class-casting?  You could imagine

`
import java.util.Map;

/**
 * To get a value from the "default request array", call {@link #get(Object)} with a String key.
 * To get an NGX variable, call {@link #getVariable(String)} with a String variable name.
 */
public interface NginxRequestVariables extends Map<String, Object> {

    /**
     * Get the value for the specified name from the NGX Variables.
     *
     * @param name
     * @return
     */
    String getVariable(String name);
}
`

together with interface method in NginxJavaRingHandler

`
    public Object[] invoke(NginxRequestVariables  request) {
`

What do you think?
