### ISSUE TITLE
Segmentation fault on shutdown

### ISSUE THREAD

**Issue by LGMAM** [nginx-clojure/nginx-clojure#216]
[Openresty](https://github.com/openresty) is a nginx+luajit distribution. [Resty](https://github.com/openresty/resty-cli) is a CLI for executing lua code in a head-less nginx instance.

> This tool works by creating a head-less nginx instance, disabling daemon, master_process, access_log, and other things it does not need. No server {} is configured hence no listening sockets are involved at all.

I have compilted nginx-clojure module in Openresty and it is working great. However, there is an error when executing [Resty](https://github.com/openresty/resty-cli). It seems that nginx-clojure is giving a segmentation fault on shutdown

`resty --gdb -e 'print(jit.version)`

it gives the following error:

```
(gdb) run
Starting program: /usr/local/openresty/nginx/sbin/nginx -p /tmp/vKNxHIMxS_/ -c conf/nginx.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
LuaJIT 2.1.0-beta3

Program received signal SIGSEGV, Segmentation fault.
0x00005555555b41ec in ngx_shm_free (shm=shm@entry=0x555555942740 <ngx_http_clojure_shared_memory>) at src/os/unix/ngx_shmem.c:35
35	        ngx_log_error(NGX_LOG_ALERT, shm->log, ngx_errno,
(gdb) backtrace
#0  0x00005555555b5fac in ngx_shm_free (shm=shm@entry=0x555555943ba0 <ngx_http_clojure_shared_memory>) at src/os/unix/ngx_shmem.c:35
#1  0x00005555556b4d50 in ngx_http_clojure_module_exit (cycle=<optimized out>) at /tmp/openresty-1.13.6.2/../nginx-clojure-0.4.5/src/c/**ngx_http_clojure_module.c:968**
#2  0x00005555555b7551 in ngx_master_process_exit (cycle=cycle@entry=0x555555985130) at src/os/unix/ngx_process_cycle.c:760
#3  0x00005555555b97c2 in ngx_single_process_cycle (cycle=0x555555985130) at src/os/unix/ngx_process_cycle.c:343
#4  0x0000555555590db1 in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:381
```

The offending [line](https://github.com/nginx-clojure/nginx-clojure/blob/9d35bffa1b8100cdc9cec2281b03c5374a45a73f/src/c/ngx_http_clojure_module.c#L976) in the function ngx_http_clojure_module_exit

```
ngx_shm_free(&ngx_http_clojure_shared_memory);**
```

Any hint ?

Thanks.

**Comment by xfeep** [comment]
Please try commit  50096bd.
