### ISSUE TITLE
unknown directive "jvm_path" in C:\NgInX\nginx/conf/nginx.conf:35 in windows

### ISSUE THREAD

**Issue by Ramesh666** [nginx-clojure/nginx-clojure#218]
I have tried to use the nginx-clojure with nginx. I have added nginx-clojure and clojure jars location in jvm_options. But still i am facing issue.

I am facing this issue in windows. Please help me to resolve this. Thanks!

**Comment by Ramesh666** [comment]
configuration is like below: 
Please help!!

http {
   	jvm_path "C:\Program Files\Java\jdk1.8.0_45\jre\bin\server\jvm.dll";
	
	jvm_var nginx_clojure_jar_path "C:\NgInX\nginx\lib\nginx-clojure-0.4.5.jar";
	
	jvm_var clojure_jar_path "C:\NgInX\nginx\lib\clojure-1.5.1.jar";
	
	jvm_var java_handler_jar_path "C:\NgInX\nginx\lib\secure-gateway-0.0.1.jar";
	
	jvm_options "-Djava.class.path=#{nginx_clojure_jar_path};#{java_handler_jar_path};#{clojure_jar_path}";

}

**Comment by xfeep** [comment]
It seems that your nginx was not compiled with nginx-clojure module.
Please check [this link](https://nginx-clojure.github.io/installation.html) to get more about installation.

**Comment by Ramesh666** [comment]
Thank for your quick response.
