### ISSUE TITLE
I want to block the request in NginxJavaBodyFilter class after validating token from request

### ISSUE THREAD

**Issue by Ramesh666** [nginx-clojure/nginx-clojure#220]

**Comment by Ramesh666** [comment]
Hi,

I have did validation and tried to return the new Object[] {null, null, null}  for the invalid request in filter class. But after sending this null response. no response will send back to the client. Please find the code for your reference.

            if(null != jwt) {
                return new Object[] {200, null, body};
            }  else {
                return new Object[] {null, null, null};  # return new Object[] {403, null, null}
            }

nginx.conf

location  /secure {
    handlers_lazy_init off;
    handler_type 'java';
    header_filter_name 'com.HeaderValidationFilter$JWTFilter';
}

Response:
page is keep on loading not receiving response from nginx.

**Comment by Ramesh666** [comment]
Can you please explain the same with proxy_pass for valid request after do the filter validation...

Thank you !

**Comment by xfeep** [comment]
Please check this link for more details.

http://nginx-clojure.github.io/configuration.html#25-nginx-rewrite-handler
