### ISSUE TITLE
Add documentation or support for local build package of nginx-clojure 

### ISSUE THREAD

**Issue by bmscomp** [nginx-clojure/nginx-clojure#231]
Add documentation , or how to topic for building a release in local developer machine, For now even if we lunch the build on travis-ci.org we cannot get the built artifacts

**Comment by xfeep** [comment]
@bmscomp 
There is a simple guide for [installation by source](http://nginx-clojure.github.io/installation.html) .If it is not enough, please tell us.Thanks!
