### ISSUE TITLE
#219 Reopen

### ISSUE THREAD

**Issue by dennus** [nginx-clojure/nginx-clojure#234]
After #219 bug fixing, no response return in body filter after:
 
`
long rc = NginxClojureRT.ngx_http_filter_continue_next(nr, -1, -1); //continue next header filter, using 0 in last argument not change effect`
`NginxClojureRT.ngx_http_finalize_request(nr, rc);`
`return new Object[]{status, null, old};`
where status - http status code returned from upstream, old - response body from upstream
 
Debug log contains next records:

2019/12/11 09:02:29 [debug] 2674#2674: *442 http finalize request: -2, "/test?" a:1, c:2
2019/12/11 09:02:29 [debug] 2674#2674: *442 http request count:2 blk:0
2019/12/11 09:02:29 [debug] 2674#2674: *442 jni_ngx_http_filter_continue_next, chain=1279484400u, old_chain=0u
2019/12/11 09:02:29 [debug] 2674#2674: *442 jni_ngx_http_filter_continue_next, chain=1279484400u, size=19, is_last=1
2019/12/11 09:02:29 [debug] 2674#2674: *442 http copy filter: 0 "/test?"
2019/12/11 09:02:29 [debug] 2674#2674: *442 http finalize request: 0, "/confirmation/ib/v1/workflow?" a:1, c:1

**Comment by xfeep** [comment]
@dennus Thank you very much!  Could you please give us a minimal example to reproduce it?  e.g. use a docker environment as an upstream?  If so,  we can fix it faster.

**Comment by dennus** [comment]
Hello @xfeep !
I see, that problem in https://github.com/nginx-clojure/nginx-clojure/blob/master/src/c/ngx_http_clojure_mem.c#L3090

When ngx_http_next_header_filter return NGX_AGAIN, no more try to call header/body filter will make anymore.

**Comment by xfeep** [comment]
@dennus Thanks for your suggestion! Please try commit d6dc0f7.
