### ISSUE TITLE
Error compiling nginx-clojure module with nginx

### ISSUE THREAD

**Issue by javajournals** [nginx-clojure/nginx-clojure#235]
Hi,

I get the following error when compiling nginx-clojure module with nginx:

`/Library/Developer/CommandLineTools/usr/bin/make -f objs/Makefile install
cc -c -DNGX_CLOJURE_BE_SILENT_WITHOUT_JVM -I "/Library/Java/JavaVirtualMachines/jdk1.8.0_212.jdk/Contents/Home/include" -I "/Library/Java/JavaVirtualMachines/jdk1.8.0_212.jdk/Contents/Home/include/darwin"  -pipe  -O -Wall -Wextra -Wpointer-arith -Wconditional-uninitialized -Wno-unused-parameter -Wno-deprecated-declarations -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I /Users/Downloads/nginx-clojure-0.5.1/src/c \
		-o objs/addon/c/ngx_http_clojure_mem.o \
		/Users/Downloads/nginx-clojure-0.5.1/src/c/ngx_http_clojure_mem.c
/Users/Downloads/nginx-clojure-0.5.1/src/c/ngx_http_clojure_mem.c:1911:10: error: logical not is only applied to the left hand side of this bitwise operator [-Werror,-Wlogical-not-parentheses]
                                        if (!(buf->pos[0] >> 7) & 1) { /*control frame must be FIN*/
                                            ^                   ~
/Users/Downloads/nginx-clojure-0.5.1/src/c/ngx_http_clojure_mem.c:1911:10: note: add parentheses after the '!' to evaluate the bitwise operator first
                                        if (!(buf->pos[0] >> 7) & 1) { /*control frame must be FIN*/
                                            ^
                                             (                     )
/Users/Downloads/nginx-clojure-0.5.1/src/c/ngx_http_clojure_mem.c:1911:10: note: add parentheses around left hand side expression to silence this warning
                                        if (!(buf->pos[0] >> 7) & 1) { /*control frame must be FIN*/
                                            ^
                                            (                  )
1 error generated.
make[1]: *** [objs/addon/c/ngx_http_clojure_mem.o] Error 1
make: *** [install] Error 2`

Thanks

**Comment by xfeep** [comment]
@javajournals Please try the latest commit 4b1e964. Thanks.
