### ISSUE TITLE
Question on memory consuption in combination with jvm -Xms/-Xmx and worker_processes

### ISSUE THREAD

**Issue by afiller** [nginx-clojure/nginx-clojure#237]
Hello everybody,

it may be a stupid question, but I'm a bit confused:

I setup a nginx-clojure server - **thank you by the way, it's a amazing!** - and I want to provide as many worker connections as possible. So I played around with the ```worker_processes```. Of course I also defined ```jvm_options``` for Xms and Xmx. I see all the processes on ```ps aux``` when I change this number, but I cannot see any change in RAM consumption when I change, e.g.

```
jvm_options "-Xms512m";
jvm_options "-Xmx512m";
```

to 

```
jvm_options "-Xms2048m";
jvm_options "-Xmx2048m";
```

**Now the question:**  (tl;dr)

Is my assumption correct, that each worker process multiplies the RAM consumption of nginx-clojure?

So ```-Xms512m``` with 4 worker processes should already consume 2 GB RAM at startup?

Thanks in advance, 
Andreas

**Comment by xfeep** [comment]
> Is my assumption correct, that each worker process multiplies the RAM consumption of nginx-clojure?

Yes.

> So -Xms512m with 4 worker processes should already consume 2 GB RAM at startup?

It depends.
With  `-Xms512m` every worker process, viz. jvm process, reserves 512m for the initial java heap.
The total memory used by one jvm includes three parts

- java heap
- direct memory (off heap)
- others (e.g. native thread stack, classes code, internal memory, dynamic libraries, etc)

BTW `ps aux` shows RSS which includes shared memory among jvm processes.
