### ISSUE TITLE
How to capture the nginx request body in the handler ?

### ISSUE THREAD

**Issue by sagarika-hp** [nginx-clojure/nginx-clojure#238]
I am trying to capture the request body in the handler  using inputstream ..But the inputstream is always null 

public Object[] invoke(Map<String, Object> request) {
        InputStream is = (InputStream) request.get(Constants.BODY);
        String abc = getIdFromBody(is)
        if(abc !=null)
         {  return Constants.PHASE_DONE;}
   }

private String getIdFromBody(InputStream is) {
        ObjectNode node;
        String text = null ;
        try {
             text = IOUtils.toString(is, StandardCharsets.UTF_8.name());
            logger.info("requestPayload={}", text);
          
         }

         catch (IOException e) {
            e.printStackTrace();
        }

        logger.info("didnt get entity_id ", text);
         return text;
    }

M i MISSING SOMETHING HERE ?

**Comment by xfeep** [comment]
@sagarika-hp Which type of handler do you use?
If you use rewrite/access handler, please try this directive [always_read_body](http://nginx-clojure.github.io/directives.html#user-content-always_read_body) .
