### ISSUE TITLE
java ring handler for client TLS certificate verification

### ISSUE THREAD

**Issue by rkotagiri** [nginx-clojure/nginx-clojure#247]
Is there support to extract client TLS certificate from the request map and verify the client certificate to enable 2 way TLS authentication ?
From the nginx clojure docs: https://nginx-clojure.github.io/more.html
sl-client-cert (Optional, X509Certificate) The SSL client certificate, if supplied. **This value is not supported yet.**

Please comment.

**Comment by xfeep** [comment]
Please try to use the two directives to enable two-way TLS 
1. [ssl_client_certificate](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_client_certificate)
2. [ssl_verify_client](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_client)

BTW you can get client certificate information by use `(get-ngx-var req name)` or `NginxJavaRequest.getVariable` , e.g. 

```clojure
;;; get the client subject DN
(get-ngx-var req "ssl_client_s_dn")
```

More details about ssl client variables can be found at [ngx_http_ssl_module variables](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#variables)

Note that if you use thread pool mode it's better to let nginx-clojure prefetch these variables.

e.g.

```clojure
;;; make variables prefetched to access them at non-main thread
(def my-simple-handler (with-meta my-simple-handler {"variablesNeedPrefetch" 
                                        ["ssl_client_s_dn"]}))
```

**Comment by rkotagiri** [comment]
Thank you for giving direction. I will try it out.
