### ISSUE TITLE
There seems to be a problem with the "slow I / O operations" document

### ISSUE THREAD

**Issue by dingyong666** [nginx-clojure/nginx-clojure#249]
http {}
` 
        # nginx-clojure
        jvm_path '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.282.b08-1.el7_9.x86_64/jre/lib/amd64/server/libjvm.so';
        
        jvm_var proot '/www/wwwroot/project';
        # nginx-clojure-0.5.2.jar
        jvm_var j_clib '#{proot}/core/*';
        # other jars
        jvm_var j_libs '#{proot}/libs/*';
        # for nginx-clojure handler
        jvm_var j_handler '#{proot}/handler/*';
        
        jvm_classpath '#{j_clib}:#{j_libs}:#{j_handler}';
`

------------------------------------------------------

There seems to be a problem with the "slow I / O operations" document
 
Using the jvm_options will be errors in the configuration, and you will be prompted to use the JVM_ Classpath, currently can not accurately know how to configure ，thanks you

**Comment by xfeep** [comment]
@dingyong666 Thank you!  I have fixed this issue with the document.
