### ISSUE TITLE
Java: Custom Response OR set headers on the upstream response.

### ISSUE THREAD

**Issue by Lugghawk** [nginx-clojure/nginx-clojure#254]
I am trying to write a Java handler for nginx-clojure where I can either set headers on the response from the upstream server, or stop the request from being sent upstream.

I have seen both the `NginxJavaRingHandler` and `NginxJavaHeaderFilter` but the former seems unable to attach headers to a response if we return `Constants.PHASE_DONE` (which I need to do to continue with the proxying, right?), and the latter will still send the request upstream even if we return a custom response from the handler (I must not send the request upstream in some cases).

These are the attempts that I've come up with, with some pseudo-code to fill in some blanks.

```java
// NginxJavaRingHandler
// I don't know how to set response headers here.
@Override
public Object[] invoke(Map<String, Object> req) {
    if (shouldNotProxy(req)) return new Object[] {503, null, "no"};
    if (addResponseHeaders(req)){
       // We return PHASE_DONE, but I want to stage some headers that will be added to the response
       // I don't know how to do this.
       return Constants.PHASE_DONE;
    }
    return Constants.PHASE_DONE;
}
```

```java
// NginxJavaHeaderFilter
// This still sends the request upstream.
@Override
public Object[] doFilter(int status, Map<String, Object> request, Map<String, Object> responseHeaders) {
    if (shouldNotProxy(req)) return new Object[] {503, null, "no"}; // This has still sent the request already.
    if (addResponseHeaders(req)){
       responseHeaders.addAll(headers); // This gets the headers added that I expect.
       return Constants.PHASE_DONE;
    }
    return Constants.PHASE_DONE;
}
```
I don't think that either of these handlers on their own is going to be sufficient, but I'm hoping that I'm just missing something. Another issue I'm having is that I'd rather not run the `shouldNotProxy(req)` or `addResponseHeaders(req)` functions more than once per request. 

Appreciate any help you can provide.

**Comment by xfeep** [comment]
Please try rewrite handler which can be used to change the upstream request ,e.g. Host, and control the request to be sent to the upstream server or not. Header filter can be used to change response headers.  So please try both of them.

**Comment by Lugghawk** [comment]
@xfeep Thanks. So just to confirm there is not a single spot I can do this, and instead need to run the checks twice (once when the request comes in to the rewrite_handler, and then again as we're setting up the response in the header_filter)?

**Comment by xfeep** [comment]
@Lugghawk You're right. You need check twice. BTW. request.nativeRequest() can be used to determine they have the same original request.
