### ISSUE TITLE
Java File.list() return Return garbled code

### ISSUE THREAD

**Issue by william05982** [nginx-clojure/nginx-clojure#255]
centos  locale：LANG=zh_CN.utf-8
nginx，conf/nginx.conf  no #jvm_options "-Dfile.encoding=utf-8";
  jinfo view jvm： sun.jnu.encoding = ANSI_X3.4-1968
                             file.encoding = ANSI_X3.4-1968
test   File.list() return chinese characters Return garbled code

so,modify  conf/nginx.conf: add
  jvm_options "-Dfile.encoding=utf-8";
  jvm_options "-Dsun.jnu.encoding=utf-8";
  jinfo view jvm： file.encoding=utf-8
                             sun.jnu.encoding=utf-8
test   File.list() return chinese characters Return garbled code

**Comment by xfeep** [comment]
Please add this line to your nignx.conf 

```
env LANG=zh_CN.utf-8;
```
