### ISSUE TITLE
More context  support 

### ISSUE THREAD

**Issue by shook2012** [nginx-clojure/nginx-clojure#270]
Hi,Zhang!
    Will it be possible to support the use of content_handler, rewrite_handler, access_handler, header_filter, body_filter and other methods in the context of http and server level in the future? Just like the openresty's access_by_lua_block、header_filter_by_lua_block、body_filter_by_lua_block etc.

**Comment by xfeep** [comment]
Hi @shook2012 
I don't it is difficult. It can be implemented in the next release.
If possible please say more  about your real case so that useful test cases can be added.

**Comment by shook2012** [comment]
Great!

**Comment by xfeep** [comment]
v0.6.0 supports this feature.
