### ISSUE TITLE
Dispatch incoming request to a jsp and set attribute

### ISSUE THREAD

**Issue by mcaap** [nginx-clojure/nginx-clojure#285]
Hi,

I wish to show a simple form with data populated by the server.
With a conventional java servlet, I could setAttribute in the Request and use the RequestDispatcher to forward the request to the jsp.

How do I achieve this with NginxJavaRingHandler?

**Comment by xfeep** [comment]
We prefer static html pages and restful service (e.g. Jersey) if we use java with nginx-clojure.

**Comment by mcaap** [comment]
Thank you for your quick response.
