### ISSUE TITLE
nginx 1.25.0 build error

### ISSUE THREAD

**Issue by rongfengliang** [nginx-clojure/nginx-clojure#294]
## error message

```code
../nginx-clojure/src/c/ngx_http_clojure_mem.c:682:1: error: static declaration of ‘ngx_http_close_request’ follows non-static declaration
 ngx_http_close_request(ngx_http_request_t *r, ngx_int_t rc)
 ^
In file included from ../nginx-clojure/src/c/ngx_http_clojure_mem.h:9:0,
                 from ../nginx-clojure/src/c/ngx_http_clojure_mem.c:5:
src/http/ngx_http.h:136:6: note: previous declaration of ‘ngx_http_close_request’ was here
 void ngx_http_close_request(ngx_http_request_t *r, ngx_int_t rc);
```
## solve

in ngx_http_clojure_mem.c file change ngx_http_close_request to another name ( ngx_http_close_requestv2 ) also in  ngx_http_clojure_mem.c file  change call  this function to  using new function name

[#296  ](https://github.com/nginx-clojure/nginx-clojure/pull/296)

**Comment by xfeep** [comment]
Thanks for your PR.
Starting from nginx 1.25.0, ngx_http_close_request is a public function that can be used directly without copying it.
Could you please update your PR by adding a macro check for nginx_version >= 1025000?

**Comment by rongfengliang** [comment]
@xfeep  hello, I had change it with macro 

#296

**Comment by xfeep** [comment]
@rongfengliang Thanks. I've accepted it into the master branch.
