### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by i-maravic** [nginx-clojure/nginx-clojure#33]
What's the proper way of running tests for this project?
I tried to run it with:

$ lein with-profile unittest test
1. On a run, where I use unchanged source code, I get:

...
Exception in thread "main" java.lang.NoClassDefFoundError: nginx/clojure/SuspendExecution, compiling:(clj_http/conn_mgr.clj:26:26)
...

When I remove jvm-opts "-javaagent:target/nginx-clojure-0.2.4.jar=mb" and add "src/java" and "src/clojure" to :java-source-paths and :source-paths, respectively I get the tests to compile, but I get this errors:
1. test_all.clj expects that the Nginx is up and running on localhost, but I don't know where to find configuration with which nginx should run
2. When I run all the other tests without test_all.clj, they all fail. They all have similar stack trace:

...
Testcase: testUninitialized(nginx.clojure.UninitializedTest):   Caused an ERROR
null
java.lang.NullPointerException
    at nginx.clojure.Stack.<init>(Stack.java:83)
    at nginx.clojure.Coroutine.<init>(Coroutine.java:120)
    at nginx.clojure.Coroutine.<init>(Coroutine.java:105)
    at nginx.clojure.UninitializedTest.testUninitialized(UninitializedTest.java:23)
...

This is not surprising, since the Stack constructor is accessing the static variable which wasn't initialised.

**Comment by xfeep** [comment]
Now nginx-clojure uses travis-ci. Both unit test and integration test will be auto triggered once per new commit or per pull request.
The project CI home is https://travis-ci.com/nginx-clojure/nginx-clojure
