### ISSUE TITLE
Is nginx-clojure faster than mod_jk?

### ISSUE THREAD

**Issue by werne** [nginx-clojure/nginx-clojure#59]
Is nginx-clojure faster than simply deploying to tomcat + mod_jk + apache?

What about stability? the above solution is very well known for being use by most companies.

tnx.

**Comment by kjniemi** [comment]
@werne @xfeep we did some very basic testing with both http and https on bare-metal hardware as we were curious about establishing an absolute baseline performance.

It's more than fair to say that it won't be nginx-clojure's fault if your app doesn't perform. :-)

YMMV.

**Comment by xfeep** [comment]
@kjniemi Thanks for your work and letting us know.  I'm very glad to see that.

**Comment by aadrian** [comment]
> It's more than fair to say that it won't be nginx-clojure's fault if your app doesn't perform.

Sorry but I'm not very sure about that. Would gladly like to see some reproducible benchmarks.

Apache httpd + mod_jk is very fast and reliable compared even to Apache httpd + mod rewrite/proxy (ssl termination done in Apache of course) or other rewrite/proxy solutions thanks to AJP http://tomcat.apache.org/connectors-doc/ajp/ajpv13a.html

Maybe ngingx-clojure could use AJP itself for the Tomcat integration?
