### ISSUE TITLE
nginx-clojure start

### ISSUE THREAD

**Issue by justnull** [nginx-clojure/nginx-clojure#62]
sbin  sudo ./nginx 
nginx: [emerg] unknown directive "jvm_path" in /usr/local/nginx/conf/nginx.conf:35

**Comment by xfeep** [comment]
Hi , does your nginx include nginx-clojure module?
Please run

$ ./nginx -V

If it includes nginx-clojure module the output should contains something
like

--add-module=../nginx-clojure/src/c


Please check the installation document
http://nginx-clojure.github.io/installation.html.

**Comment by xfeep** [comment]
Close it now. If there 's any other problems please reopen it.

**Comment by soufrk** [comment]
Yes, I have an issue with this. I have compiled as per your instructions, except the step where "Leiningen" is to be used for extracting "JAR", I guess. I hope that should not be causing this problem.

**Comment by xfeep** [comment]
@soufrk Is it possible that `make install`  failed without root permission?
The message `unknown directive "jvm_path"` means the nginx has not been compiled with nginx-clojure module.

**Comment by soufrk** [comment]
Yes, that seemed to have solved the issue. But, now there is a different one.
`nginx: [emerg] no such dir: "libs/" (2: No such file or directory) in /usr/local/nginx/conf/nginx.conf:23`

Any clues about this one ??

**Comment by xfeep** [comment]
By default nginx-clojure will check all path defined by directive `jvm_classpath`.
If the path does not exist or the user by which we run nginx has no access permission to read the path/file nginx-clojure will emit error messages.
Please check line 23 in your nginx.conf.

**Comment by xfeep** [comment]
BTW we can use 

```nginx
    jvm_classpath_check off;
```

to disable the check.

**Comment by soufrk** [comment]
That helps !! But wondering why it is there, if it has to be skipped !! 
Thanks a lot
