### ISSUE TITLE
proxy_cache_path导致crash

### ISSUE THREAD

**Issue by zhangkaitao** [nginx-clojure/nginx-clojure#64]
如果添加如下配置
proxy_cache_path  /export/servers/nginx/proxy_cache levels=1:2 keys_zone=cache_product:200m inactive=1m max_size=1g;

2015/02/03 11:45:16 [error] 13845#0: jvm may be mad for wrong options! See hs_err_pid****.log for detail! restarted 2
2015/02/03 11:45:16 [error] 13843#0: jvm may be mad for wrong options! See hs_err_pid****.log for detail! restarted 3
2015/02/03 11:45:16 [alert] 13697#0: worker process 13843 exited with fatal code 2 and cannot be respawned

**Comment by xfeep** [comment]
Hi, Thanks for your report about the issue.

It's a  bug of nginx-clojure.

This bug will cause nginx proxy cache manager processes fail to start.

We 'll fix it soon.

Regards.
Xfeep

**Comment by xfeep** [comment]
Hi, this issue has been fixed by commit cddfe85 . Please try it. Thanks again!
