### ISSUE TITLE
could not initialize content handler

### ISSUE THREAD

**Issue by TonyWuLihu** [nginx-clojure/nginx-clojure#77]
encountered the following error while try to access the clojure location 
2015/06/12 12:48:39 [error] 28733#0: invalid clojure content_handler code : (fn[req]
                          {
                            :status 200,
                            :headers {"content-type" "text/plain"},
                            :body  "Hello Clojure & Nginx!" ;response body can be string, File or Array/Collection/Seq of them
                            })
Exception in thread "main" java.lang.RuntimeException: can not load factory:nginx.clojure.clj.NginxClojureHandlerFactory
        at nginx.clojure.NginxHandlerFactory.fetchFactory(NginxHandlerFactory.java:35)
        at nginx.clojure.NginxHandlerFactory.fetchHandler(NginxHandlerFactory.java:42)
        at nginx.clojure.NginxClojureRT.registerCode(NginxClojureRT.java:696)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class nginx.clojure.clj.Constants
        at nginx.clojure.clj.NginxClojureHandlerFactory.<init>(NginxClojureHandlerFactory.java:23)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:379)
        at nginx.clojure.NginxHandlerFactory.fetchFactory(NginxHandlerFactory.java:32)
        ... 2 more

**Comment by TonyWuLihu** [comment]
I think it might be something related to classpath setting, below is my config 

    jvm_path  "/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.79.x86_64/jre/lib/amd64/server/libjvm.so";
    jvm_var nginx_clojure_jar '/usr/local/nginx-clojure-0.3.0/target/nginx-clojure-0.3.0.jar';
    jvm_options "-javaagent:#{nginx_clojure_jar}=mb";
    jvm_options "-Xbootclasspath/a:#{nginx_clojure_jar}:jars/clojure-1.5.1.jar";
    jvm_options "-Djava.class.path=/usr/local/nginx-clojure-0.3.0/target/nginx-clojure-0.3.0.jar";
    jvm_options "-Xms1024m";
    jvm_options "-Xmx1024m";
    server {
        listen       80;

**Comment by xfeep** [comment]
Please check your clojure runtime jar file.
In your nginx.conf it is `jars/clojure-1.5.1.jar`. Does it exist ? Does nginx worker processes has permission to access it?

**Comment by TonyWuLihu** [comment]
Sorry, my careless mistake. Yes, it's caused by the permission indeed. Thanks for your help !

**Comment by soufrk** [comment]
Any other simpler way to specify just the JAR location, without having to specify JVM classpath as well ?

**Comment by xfeep** [comment]
Below is  from http://nginx-clojure.github.io/directives.html#jvm_classpath

`jvm_classpath`

* **Syntax**:	**jvm_classpath** *classpaths*;
* **Default**:	—
* **Context**:	http

Defines class paths those are separated by "`:`" (Unix like OS) or "`;`" (Windows) . When '`/*`' is used after a directory path all files and direct sub-directories will be used as the jvm class path entries. e.g. If /opt/mylibs has below structure.

```
/opt/mylibs/
-----------/a.jar
-----------/b.jar
-----------/c.zip     
-----------/classes   (direct sub-directory)
-----------/resources (direct sub-directory)
```

And we use below declaration.

```nginx
jvm_classpath /opt/mylibs/*;
## there are two equivalent declarations which use quote mark. It is useful when there are some special chars such as ' ', ';' etc.
## jvm_classpath '/opt/mylibs/*';
## jvm_classpath "/opt/mylibs/*";

```
It is equivalent to 

```nginx
jvm_options '-Djava.class.path=/opt/mylibs/a.jar:/opt/mylibs/b.jar:/opt/mylibs/c.zip:/opt/mylibs/classes:/opt/mylibs/resources'
```

We can also define serveral class paths by using separator `:` (UNIX like OS) or `;` (Windows), e.g.

```nginx
jvm_classpath /opt/mylibs/*:/opt/my-another-libs/*:/opt/my-resources;
## for windows user
# jvm_classpath c:/mylibs/*;c:/my-another-libs/*;c:/my-resources;
```

**Note that the behavior about wildcard `*` here is different from `-cp` or `-classpath` option
of jdk/jre java command where wildcard `*` only means jar files and non-jar files and sub-directories
won't be included.**
