### ISSUE TITLE
Class cast error while starting up nginx-clojure with tomcat bridge

### ISSUE THREAD

**Issue by Asprelis** [nginx-clojure/nginx-clojure#81]
Hello! You made great thing! 
I have an error whet trying to run nginx with bridge to tomcat:

    java.lang.ClassCastException: java.lang.Class cannot be cast to clojure.lang.IFn
	at nginx.clojure.clj.NginxClojureHandlerFactory.newInstance(NginxClojureHandlerFactory.java:45)
	at nginx.clojure.NginxHandlerFactory.fetchHandler(NginxHandlerFactory.java:46)
	at nginx.clojure.NginxClojureRT.registerCode(NginxClojureRT.java:811)
    2015/07/06 18:07:07 [error] 27236#30856: invalid clojure content_handler code : nginx.clojure.bridge.NginxBridgeHandler
        Exception in thread "main" 

I'm running nginx on windows x64 with as administrator, so file access should not be a problem.
Also i double checked existence of required jars, and path to them.
I'm trying to follow these giudes: [tomcat guide](https://github.com/nginx-clojure/nginx-clojure/tree/master/nginx-tomcat8) and [nginx-clojure quickstart](https://nginx-clojure.github.io/quickstart.html)
Here is my nginx.conf file:

 
	###you can uncomment next two lines for easy debug
	###Warning: if master_process is off, there will be only one nginx worker running. Only use it for debug propose.

	#daemon  off;

	master_process  off;

	worker_processes  1;

	events {
		worker_connections  1024;
	}

	http {
		include       mime.types;
		default_type  application/octet-stream;

		sendfile        on;

		keepalive_timeout  65;

		#gzip  on;
		
		jvm_path "C:/Program Files/Java/jdk1.8.0_05/jre/bin/server/jvm.dll";
		
		jvm_var my_other_jars 'D:/nginx-closure/clojure-1.5.1.jar';
		
		###jvm_options can be repeated once per option. # note that : - unix, ; - windows separators
		jvm_options "-Djava.class.path=jars/nginx-clojure-0.4.0.jar;#{my_other_jars}";

		server {
			listen       8080;
			server_name  localhost;

			#charset koi8-r;

			#access_log  logs/host.access.log  main;
			
			# redirect server error pages to the static page /50x.html
			#
			error_page   500 502 503 504  /50x.html;
			location = /50x.html {
				root   html;
			}

		  location / {

			  content_handler_name 'nginx.clojure.bridge.NginxBridgeHandler';

			  ##Tomcat 8 installation path
			  content_handler_property system.catalina.home 'D:/nginx-closure/apache-tomcat-8.0.23';
			  content_handler_property system.catalina.base '#{catalina.home}';

			  ##uncomment this to disable websocket perframe-compression
			  #content_handler_property system.org.apache.tomcat.websocket.DISABLE_BUILTIN_EXTENSIONS true;

			  ##log manger
			  content_handler_property system.java.util.logging.manager 'org.apache.juli.ClassLoaderLogManager';

			  ## all jars or direct child directories will be appended into the classpath of this bridge handler's class-loader
			  content_handler_property bridge.lib.dirs '#{catalina.home}/lib;#{catalina.home}/bin'; #dont forget to change ; to : on unix

			  ##set nginx tomcat8 bridge implementation jar and other jars can also be appended here
			  content_handler_property bridge.lib.cp 'D:/nginx-closure/nginx-clojure-0.4.0/nginx-1.8.0/jars/nginx-tomcat8-0.1.0.jar';

			  ##The implementation class of nginx-clojure bridge handler for Tomcat 8
			  content_handler_property bridge.imp 'nginx.clojure.tomcat8.NginxTomcatBridge';

			  ##ignore nginx filter, default is false
			  #content_handler_property ignoreNginxFilter false;

			  ##when dispatch is false tomcat servlet will be executed in main thread.By default dispatch is false
			  ##when use websocket with tomcat it must be set true otherwise maybe deadlock will happen.
			  #content_handler_property dispatch false;

			  gzip on;
			  gzip_types text/plain text/css 'text/html;charset=ISO-8859-1' 'text/html;charset=UTF-8'; 

			  ##if for small message, e.g. small json/websocket message write_page_size can set to be a small value
			  #write_page_size 2k;
		  }		
			
		   
		}

	}

**Comment by xfeep** [comment]
Hi,

Thanks for report this issue!
Please add

content_handler_type java;

at the location block or add

jvm_handler_type java;

at the http block for global handler type setting.

**Comment by xfeep** [comment]
I  updated the doc too. 
1. http://nginx-clojure.github.io/more.html#310-embeding-tomcat
2. https://github.com/nginx-clojure/nginx-clojure/tree/master/nginx-tomcat8

**Comment by Asprelis** [comment]
Yes, that fixed the problem! Thank you!
