### ISSUE TITLE
how to make unbelievably long classpaths work reliably

### ISSUE THREAD

**Issue by kjniemi** [nginx-clojure/nginx-clojure#94]
While this is an issue it's also a document on how to get it done if one really has to.

I have a "project" which has in excess of 150 jars (don't ask) that have to be in its classpath for it to run. Originally written as a standalone application for the command line it works well using `-cp lib/*` however that cannot be used with nginx-clojure.

As a workaround I tried using jvm_var and jvm_options as follows:

```
jvm_var lib "/path/to/library";
jvm_var jar0 "#{lib}xstream-1.4.4.jar:#{lib}activemq-stomp.jar:#{lib}activemq-broker.jar:#{lib}jms.jar";
...
jvm_var jar17 "#{lib}gson.jar:#{lib}diffutils.jar:#{lib}jdom.jar:#{lib}batik-svggen.jar:#{lib}batik-dom.jar:#{lib}batik-script.jar:#{lib}batik-parser.jar:#{lib}batik-swing.jar";

jvm_options "-Djava.class.path=#{jar0}:#{jar1}:#{jar2}:#{jar3}:#{jar4}:#{jar5}:#{jar6}:#{jar7}:#{jar8}:#{jar9}:#{jar10}:#{jar11}:#{jar12}:#{jar13}:#{jar14}:#{jar15}:#{jar16}:#{jar17}:#{jar18}";
```

The reason for having to split jvm_var on several lines and using variable expansion is nginx's builtin parser which has a maximum line length which got exceeded quickly. It also turns out that `-cp` and `-Djava.class.path` are not the same thing at all. Magically some of the jars will silently not load for one or another reason and the errors were always related to missing classes.

The only way I could figure to get the whole thing to work was to create a jar which contains a `META-INF/MANIFEST.MF` with the following contents:

```
Premain-Class: nginx.clojure.wave.JavaAgent
Main-Class: clojure.main
 /path/to/1st.jar
 /path/to/2nd.jar
 /path/to/150th.jar

```

**Comment by xxxenic** [comment]
For some reason, a very long -Djava.class.path=.. fails, this is probably a JVM limitation that we are not aware of.

It is possible that nginx-clojure cannot really help us here, but for anyone experiencing the same problem, you must modify your current nginx-clojure.jar/META-INF/MANIFEST.MF (or create a custom .jar containing required values).

The MANIFEST.MF Must contain a 'Class-Path: ' variable, which must be followed by the jars to include. The trick is, that each line for the Class-Path must be <= 72bytes, and each new line must start with a single space (' ')

Good pointers:
http://stackoverflow.com/questions/3057841/too-long-line-in-manifest-file-while-trying-to-create-jar
http://docs.oracle.com/javase/1.5.0/docs/guide/jar/jar.html

**Comment by xfeep** [comment]
Please try to use `-Djava.ext.dirs=...` .

Quote the comment from [Nginx-Clojure Quick Start](http://nginx-clojure.github.io/quickstart.html) here :
```shell
###or we can put jars in some directories, e.g. jars-dir1, jars-dir2
###so that all jars or direct sub directories from these directories will be appended to the jvm classpath
##Note: if you use build-in extensions (e.g. SUN JCE) from jdk please append these dirs, e.g. the value of 
##            System.getProperty("java.ext.dirs")
jvm_options "-Djava.ext.dirs=jars-dir1:jars-dir2";  
```

Another discussion about it can be found from #25 .

**Comment by kjniemi** [comment]
@xfeep thanks for the tip, we were aware of it but cannot use it as the following isn't possible on the fly:

```jvm_options "-Djava.ext.dirs=System.getProperty('java.ext.dirs'):our/custom/dir';```

(as you mention, JSSE breaks)

**Comment by xfeep** [comment]
@kjniemi  In your case do you need that jvm_options won't be updated at deployment period?  e.g. use some relative paths?

If so shell script may be helpful to get the value of System.getProperty('java.ext.dirs') and re-generate the nginx.conf.

Another choice is to use `NginxBridgeHandler` and `NginxBridge`.  `content_handler_property bridge.lib.dirs` can be used to define a classpath dirs without overwrite the default value of `java.ext.dirs`.

The subproject nginx-tomcat8 is a typical example. See [configuration example](https://github.com/nginx-clojure/nginx-clojure/tree/master/nginx-tomcat8#configuration) and [NginxTomcatBridge](https://github.com/nginx-clojure/nginx-clojure/blob/master/nginx-tomcat8/src/java/nginx/clojure/tomcat8/NginxTomcatBridge.java).

**Comment by xfeep** [comment]
BTW if I am not wrong the max length of nginx configuration line is 4k, on nginx-clojure the max length of jvm_options expansion is 8k.

**Comment by kjniemi** [comment]
@xfeep thank you for your tips :) I think we're okay with the MANIFEST.MF way of doing it as I can get that triggered automatically during the packaging phase.

Similarly we generate the jvm_path string at build time depending if we're compiling with JDK6 or JDK8.

**Comment by xfeep** [comment]
@kjniemi  @xxxenic  A new directive [jvm_classpath](https://nginx-clojure.github.io/directives.html#jvm_classpath) was added since [0.4.3](https://github.com/nginx-clojure/nginx-clojure/releases/tag/v0.4.3). I wish it can make things easier. Thanks.

**Comment by kjniemi** [comment]
@xfeep thanks, I noticed :)

**Comment by knasim** [comment]
i'm getting this:  
 `2016/12/16 23:08:34 [error] 19730#0: can not initialize jvm for load dynamic lib, maybe wrong jvm_path!`


my jvm_path is:

`jvm_path /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-2.b15.el7_3.x86_64/`

also tried:

`jvm_path /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-2.b15.el7_3.x86_64/jre`

**Comment by knasim** [comment]
Never mind !  
it's supposed be the location to libjvm.so file
`i.e /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.111-2.b15.el7_3.x86_64/jre/lib/amd64/server/libjvm.so`
